import json
# Arabisch: Plural-Formen zero/one/two/few/many/other (Intl.PluralRules('ar')).
def A(one,two,few,many,other=None,zero=None):
    d={"one":one,"two":two,"few":few,"many":many,"other":other or many}
    if zero: d["zero"]=zero
    return d
U=lambda s,p: A(s,s,p,s,s)  # Einheit: 1 → Singular, 3–10 → Plural, 11+ → Singular (Tamyiz)
t = {
 "allg.fertig":"تم","allg.gespeichert":"تم الحفظ","allg.hinzufuegen":"إضافة","allg.loeschen":"حذف","allg.los":"لنبدأ","allg.mehr":"أكثر","allg.nochmal":"حاول مرة أخرى",
 "allg.schliessen":"إغلاق","allg.senden":"إرسال","allg.spaeter":"لاحقاً","allg.speichern":"حفظ","allg.weiter":"متابعة","allg.weniger":"أقل","allg.zurueck":"رجوع",
 "ampel.gut":"كل شيء جيد","ampel.knapp":"يقترب من النفاد","ampel.knapp_kurz":"قليل","ampel.sofort":"فوراً",
 "anmelden.titel":"أهلاً وسهلاً","anmelden.unter":"من أنت؟","anmelden.ich_chef":"أنا المدير","anmelden.ich_chef_unter":"إنشاء مطعم أو تسجيل الدخول",
 "anmelden.ich_mitarbeiter":"أعمل هنا","anmelden.ich_mitarbeiter_unter":"بالرمز من المدير","anmelden.anmelden":"تسجيل الدخول","anmelden.neu":"جديد هنا",
 "anmelden.konto_anlegen":"إنشاء حساب","anmelden.email":"البريد الإلكتروني","anmelden.passwort":"كلمة المرور (8 أحرف على الأقل)","anmelden.code":"الرمز من المدير",
 "anmelden.dein_name":"اسمك الأول","anmelden.mail_bestaetigen":"اقتربنا: أرسلنا رسالة إلى {email}. اضغط على الرابط فيها من فضلك.",
 "anmelden.demo_hinweis":"عرض تجريبي: بدون خادم، للمشاهدة فقط. التعرّف محاكاة.",
 "antwort.noch_da":"متوفر","antwort.brauchst":"تحتاج","antwort.fehlt":"ينقص",
 "assistent.morgen":"صباح الخير","assistent.tag":"نهارك سعيد","assistent.abend":"مساء الخير",
 "assistent.gescannt":"تم المسح اليوم · {zeit} · {wer}","assistent.teilweise":"تم مسح {n} من {von} اليوم",
 "assistent.nicht_gescannt":"لم يتم المسح اليوم","assistent.es_fehlt":"ينقص: {bereiche}","assistent.zahlen_alt":"الأرقام من آخر مسح: {wann}.",
 "assistent.selbst_scannen":"امسح الآن","assistent.briefing":"ملخص المساء","assistent.stand_jetzt":"الوضع الآن","assistent.vorlesen":"قراءة بصوت عالٍ",
 "assistent.zum_bestand":"إلى المخزون","assistent.wichtig":A("أمر واحد مهم","أمران مهمان","{n} أمور مهمة","{n} أمراً مهماً"),"assistent.hinweise":"تنبيهات","assistent.tagesgericht":"فكرة طبق اليوم",
 "assistent.tagesgericht_fehler":"لا توجد فكرة الآن.","assistent.frag_mich":"اسألني شيئاً …",
 "assistent.verworfen":"لا أستطيع قول ذلك بثقة الآن. امسح من جديد أو اسأل بطريقة أخرى.",
 "bestaetigen.titel":"هذا ما تعرّفت عليه","bestaetigen.unter":"هل كل شيء صحيح؟ اضغط على مربع لتغييره.",
 "bestaetigen.test_titel":"عُدّ بنفسك من فضلك","bestaetigen.test_unter":"اختبار الدقة: اضغط على كل مربع وأدخل العدد الحقيقي.",
 "bestaetigen.nichts_erkannt":"لم أتعرّف على شيء من الكتالوج. أضفه يدوياً أو التقط صورة جديدة.",
 "bestaetigen.unsicher":"غير متأكد","bestaetigen.von_hand":"مضاف","bestaetigen.zaehlen":"عُدّ","bestaetigen.fehlt_etwas":"هل ينقص شيء؟",
 "bestaetigen.speichern":"كل شيء صحيح – احفظ","bestaetigen.noch_offen":A("بقي {n} للعدّ","بقي {n} للعدّ","بقي {n} للعدّ","بقي {n} للعدّ"),"bestaetigen.noch_foto":"التقط صورة أخرى",
 "bestaetigen.mhd":"صالح حتى (إن كان على الملصق)","bestaetigen.nicht_da":"غير موجود ({zahl})","bestaetigen.schon_gespeichert":"هذا المسح محفوظ مسبقاً.",
 "bestand.titel":"المخزون","bestand.letzter_scan":"آخر مسح: {wann}","bestand.ware_im_lager":"البضاعة في المخزن","bestand.weggeworfen_monat":"الهدر في {monat}",
 "bestand.ohne_preis":A("منتج واحد بدون سعر","منتجان بدون سعر","{n} منتجات بدون سعر","{n} منتجاً بدون سعر"),"bestand.ampel":"إشارة المرور","bestand.laeuft_bald_ab":"تنتهي صلاحيته قريباً",
 "bestand.mhd_berechnet":"تقديري (بدون ملصق)","bestand.alles":"كل ما في المخزن","bestand.scan":"المسح: {wann}","bestand.mindestens":"الحد الأدنى: {menge}",
 "bestand.leer":"لا توجد منتجات في الكتالوج بعد.","bestand.produkte_anlegen":"أضف منتجات",
 "briefing.laeuft_ab":"تنتهي صلاحية {produkt} {wann}.","briefing.abgelaufen":"انتهت صلاحية {produkt}.","briefing.nichts_laeuft_ab":"لا شيء تنتهي صلاحيته في اليومين القادمين.",
 "briefing.knapp":"{produkt} يقترب من النفاد.","briefing.bestellen":"اطلب {menge}","briefing.alles_da":"كل شيء فوق الحد الأدنى.",
 "briefing.einkauf":"مشتريات الغد:","briefing.artikel":A("صنف واحد","صنفان","{n} أصناف","{n} صنفاً"),
 "demo.bestand_satz":"{produkt}: متوفر {menge}.","demo.einkauf_satz":A("عليك طلب صنف واحد.","عليك طلب صنفين.","عليك طلب {n} أصناف.","عليك طلب {n} صنفاً."),
 "demo.reicht_ja":"نعم، يكفي.","demo.reicht_nein":"لا، ينقص حوالي {menge}.","demo.zu_wenig_daten":"لا توجد مسوح كافية لذلك بعد. بعد أيام قليلة أستطيع التقدير.",
 "demo.quelle_bestand":"من آخر مسح لك.","demo.quelle_verbrauch":"تقدير من مسوحك في آخر {tage} يوماً.","demo.quelle_weg":"من بلاغات الهدر.",
 "demo.weg_satz":"{betrag} هذا الشهر.","demo.unbekannt":"في العرض التجريبي أفهم فقط: الطلب، «كم لدينا من …؟»، «هل يكفي …؟» والهدر.",
 "demo.tagesgericht":"طبق {produkt}.","demo.tagesgericht_grund":"يستهلك {produkt} الذي تنتهي صلاحيته قريباً.",
 "einheit.kiste":U("صندوق","صناديق"),"einheit.packung":U("علبة","علب"),"einheit.stueck":U("قطعة","قطع"),"einheit.becher":U("كوب","أكواب"),
 "einheit.beutel":U("كيس","أكياس"),"einheit.flasche":U("زجاجة","زجاجات"),"einheit.dose":U("علبة معدنية","علب معدنية"),"einheit.eimer":U("دلو","دلاء"),
 "einheit.sack":U("شوال","شوالات"),"einheit.karton":U("كرتونة","كراتين"),"einheit.glas":U("مرطبان","مرطبانات"),"einheit.netz":U("شبكة","شبكات"),
 "einheit.spiess":U("سيخ","أسياخ"),"einheit.kg":U("كغ","كغ"),"einheit.l":U("لتر","لتر"),
 "einkauf.titel":"مشتريات الغد","einkauf.erstellt":"أعدّها المساعد · الوضع: {wann}","einkauf.muessen":A("صنف يجب طلبه","صنفان يجب طلبهما","أصناف يجب طلبها","صنفاً يجب طلبه"),
 "einkauf.nichts":"لا شيء للطلب. كل شيء فوق الحد الأدنى.","einkauf.noch_da":"متوفر: {menge}","einkauf.laeuft_ab":"تنتهي صلاحيته اليوم",
 "einkauf.email":"بريد إلكتروني","einkauf.teilen_titel":"مشتريات {datum}:","einkauf.anzahl":A("صنف واحد","صنفان","{n} أصناف","{n} صنفاً"),
 "einrichtung.schritt":"الخطوة {n} من {von}","einrichtung.betrieb_titel":"مطعمك","einrichtung.betrieb_name":"اسم المطعم",
 "einrichtung.bereiche_titel":"الأقسام وأماكن التصوير","einrichtung.produkte_titel":"المنتجات","einrichtung.team_titel":"دعوة الموظفين",
 "einrichtung.iphone_titel":"ضعه على الهاتف","einrichtung.fertig":"تم – لنبدأ",
 "einstellungen.titel":"الإعدادات","einstellungen.modus":"الوضع","einstellungen.hell":"فاتح","einstellungen.dunkel":"داكن","einstellungen.auto":"تلقائي",
 "einstellungen.akzent":"لون التمييز","einstellungen.akzent_warum":"الأخضر والأصفر والأحمر غير متاحة – فهي ألوان إشارة المرور.",
 "einstellungen.glas":"الزجاج","einstellungen.klar":"شفاف","einstellungen.getoent":"ملوّن","einstellungen.bewegung":"الحركة","einstellungen.bewegung_unter":"رسوم متحركة قصيرة عند الفتح",
 "einstellungen.sprache":"اللغة","einstellungen.push":"الإشعارات","einstellungen.push_unter":"الأمور المهمة وملخص المساء على الهاتف",
 "einstellungen.betrieb":"المطعم","einstellungen.erinnerung":"تذكير المسح للموظفين","einstellungen.loeschfrist":"حذف صور المسح بعد",
 "einstellungen.tage":A("يوم واحد","يومين","{n} أيام","{n} يوماً"),"einstellungen.loeschfrist_warum":"قد يظهر الموظفون في الصور. الأرقام المتعرّف عليها تبقى.",
 "einstellungen.test":"اختبار الدقة","einstellungen.test_unter":"الموظفون يعدّون بأنفسهم دون رؤية رقم الذكاء الاصطناعي",
 "einstellungen.abmelden":"تسجيل الخروج","einstellungen.demo_reset":"إعادة ضبط العرض التجريبي",
 "akzent.blau":"أزرق","akzent.lila":"بنفسجي","akzent.petrol":"أزرق مخضر",
 "fehler.unbekannt":"حدث خطأ ما.",
 "fehler.speicher_blockiert":"التطبيق ما زال مفتوحًا في نافذة أخرى. أغلقه هناك وحاول مرة أخرى.",
 "fehler.verbindung":"لا يوجد اتصال بالخادم.","fehler.laden":"تعذّر التحميل.",
 "fehler.speichern":"تعذّر الحفظ.","fehler.nicht_angemeldet":"سجّل الدخول من جديد من فضلك.","fehler.server":"أبلغ الخادم عن خطأ.",
 "fehler.foto":"تعذّر رفع الصورة.","fehler.anmelden":"لم ينجح تسجيل الدخول. تحقق من البريد وكلمة المرور.",
 "fehler.registrieren":"تعذّر إنشاء الحساب.","fehler.beitreten":"لم ينجح الانضمام.","fehler.code_ungueltig":"الرمز خاطئ أو مستخدم مسبقاً.",
 "fehler.sprache":"تعذّر تحويل الكلام. اكتب من فضلك.","fehler.sprache_demo":"الإدخال الصوتي يحتاج الخادم – في العرض التجريبي اكتب من فضلك.",
 "fehler.demo":"غير ممكن في العرض التجريبي.","fehler.keine_kamera":"لا توجد كاميرا متاحة للمتصفح على هذا الجهاز.","fehler.kein_mikrofon":"الميكروفون غير متاح. اكتب من فضلك.",
 "fehler.push_ios_installieren":"على الآيفون تعمل الإشعارات فقط إذا كان التطبيق على الشاشة الرئيسية.","fehler.push_nicht_moeglich":"هذا الجهاز لا يستقبل الإشعارات.",
 "fehler.push_ios_faehigkeit":"الإشعارات غير مفعّلة بعد في هذه النسخة من التطبيق. يضبطها المدير مرة واحدة في Xcode.","fehler.push_abgelehnt":"تم رفض الإشعارات. اسمح بها في إعدادات الهاتف.","fehler.push_nicht_eingerichtet":"الإشعارات غير مفعّلة على الخادم بعد.",
 "genauigkeit.titel":"دقة التعرّف","genauigkeit.erklaerung":"ما تعرّف عليه الذكاء الاصطناعي مقارنة بما تم عدّه عند التأكيد. آخر 30 يوماً.",
 "genauigkeit.keine_daten":"لا توجد مسوح مؤكدة بعد.","genauigkeit.genau":"صحيح تماماً","genauigkeit.gezaehlt":"تم العدّ","genauigkeit.uebersehen":"فائت",
 "genauigkeit.zeile":"{genau} من {n} صحيح · فرق {abw} في المتوسط",
 "gespeichert.titel":"تم الحفظ.","gespeichert.danke":"شكراً يا {name}. المدير يرى كل شيء الآن.","gespeichert.zusammenfassung":A("منتج واحد · {bereich} · {zeit}","منتجان · {bereich} · {zeit}","{n} منتجات · {bereich} · {zeit}","{n} منتجاً · {bereich} · {zeit}"),
 "gespeichert.als_naechstes":"التالي: {bereich}","gespeichert.weiter_scannen":"تابع المسح","gespeichert.fertig_heute":"انتهيت لليوم","gespeichert.alles_fertig":"تم مسح كل الأقسام اليوم.",
 "gespraech.leer":"اسألني عن المخزن – كتابةً أو بالميكروفون.","gespraech.auf_liste":"أُضيف إلى قائمة المشتريات.","gespraech.daten_alt":"البيانات قديمة – امسح من جديد من فضلك.",
 "gespraech.schaetzung":"تقدير","gespraech.stand":"الوضع: مسح {wann}.","gespraech.verworfen_warum":"رقم في إجابتي لم يكن في بياناتك – لذلك لم أعرضه.",
 "hinweis.abgelaufen":"انتهت صلاحية {produkt}.","hinweis.laeuft_ab":"تنتهي صلاحية {produkt} {wann}.","hinweis.leer":"نفد {produkt}.","hinweis.knapp":"{produkt} يقترب من النفاد.",
 "hinweis.bestellen":"اطلب {menge}","hinweis.fehlen":"ينقص {menge}.","hinweis.nicht_gescannt":"لم يتم المسح اليوم.","hinweis.zur_liste":"إلى قائمة المشتريات","hinweis.erledigt":"تم",
 "installieren.titel":"ضع التطبيق على الهاتف","installieren.schon":"التطبيق موجود على الشاشة الرئيسية.",
 "installieren.warum_ios":"على الآيفون تصل الإشعارات فقط إذا كان التطبيق على الشاشة الرئيسية. في Safari:",
 "installieren.warum":"هكذا تضع التطبيق على الشاشة الرئيسية:","installieren.ios_1":"اضغط «مشاركة» في الأسفل (مربع بسهم للأعلى).",
 "installieren.ios_2":"اختر «إضافة إلى الشاشة الرئيسية».","installieren.ios_3":"اضغط «إضافة» في الأعلى.","installieren.ios_4":"من الآن افتح The Chef من الأيقونة.",
 "installieren.andere_1":"افتح القائمة (⋮) في الأعلى.","installieren.andere_2":"اختر «تثبيت التطبيق» أو «إضافة إلى الشاشة الرئيسية».",
 "katalog.bereiche":"الأقسام وأماكن التصوير","katalog.produkte":"المنتجات","katalog.bereiche_erklaerung":"الأقسام هي الأماكن التي تُمسح كل يوم. لكل قسم أماكن تصوير ثابتة – التصوير بنفس الطريقة يعني عدّاً أدق.",
 "katalog.mindest_vorschlag":"اقتراح من المسح: {menge}. الاستهلاك حوالي {pro_tag} يومياً (آخر {tage} أيام) – يكفي {reichweite} أيام.","katalog.mindest_zu_wenig":"يظهر اقتراح بعد بضعة أيام من المسح.","katalog.uebernehmen":"اعتمد","katalog.positionen":"أماكن التصوير","katalog.position":"مكان التصوير","katalog.position_neu":"أضف مكان تصوير","katalog.mit_foto":"مع صورة مرجعية","katalog.ohne_foto":"بدون صورة مرجعية بعد",
 "katalog.bereich_neu":"أضف قسماً","katalog.eigener_bereich":"اسم خاص …","katalog.referenzfoto":"التقط صورة مرجعية",
 "katalog.referenzfoto_erklaerung":"صوّر مرة كما ستصوّر كل يوم. تظهر الصورة شبه شفافة كمساعدة عند المسح.",
 "katalog.wirklich_loeschen":"هل تريد الحذف فعلاً؟ السجل يبقى.","katalog.name":"الاسم","katalog.uebersetzen":"اقترح لغات أخرى","katalog.vorschlag":"اقتراح – تحقق من فضلك",
 "katalog.produkte_erklaerung":"صوّر كل منتج مرة وحدّد طريقة عدّه. الذكاء الاصطناعي يعدّ الوحدات فقط ويحوّل بنفسه.",
 "katalog.produkt_neu":"أضف منتجاً","katalog.noch_keine":"لا توجد منتجات بعد.","katalog.foto":"صورة المنتج","katalog.foto_warum":"تساعد الذكاء الاصطناعي على التعرّف.",
 "katalog.kategorie":"النوع","katalog.wie_zaehlen":"كيف يُعدّ؟","katalog.wie_zaehlen_unter":"ماذا ترى على الرف؟ الصندوق، الكوب، القطعة …",
 "katalog.zaehleinheit":"الوحدة على الرف","katalog.inhalt":"المحتوى لكل وحدة (اختياري)","katalog.basiseinheit":"بـ","katalog.beispiel":"1 {einheit} = {menge} {basis}",
 "katalog.mindestbestand":"الحد الأدنى ({einheit})","katalog.haltbarkeit":"الصلاحية (أيام)","katalog.preis":"السعر لكل {einheit} باليورو (اختياري)","katalog.wo":"أين يُحفظ؟",
 "kategorie.fleisch":"لحوم","kategorie.fisch":"سمك","kategorie.gemuese":"خضار","kategorie.obst":"فواكه","kategorie.milch":"ألبان","kategorie.brot":"خبز وعجين",
 "kategorie.tiefkuehl":"مجمّدات","kategorie.trocken":"مواد جافة","kategorie.getraenke":"مشروبات","kategorie.sonstiges":"أخرى",
 "kosten.titel":"تكاليف الذكاء الاصطناعي","kosten.letzte_30":"آخر 30 يوماً","kosten.zeile":A("طلب واحد · متوسط {je} · متوسط {tokens} رمز","طلبان · متوسط {je} · متوسط {tokens} رمز","{n} طلبات · متوسط {je} · متوسط {tokens} رمز","{n} طلباً · متوسط {je} · متوسط {tokens} رمز"),
 "kosten.keine":"لا تكاليف بعد.","kosten.je_betrieb":"لكل مطعم","kosten.hinweis":"محوّلة من الدولار بسعر ثابت. فاتورة Anthropic هي المرجع.",
 "kosten.scan":"التعرّف في المسح","kosten.assistent":"المساعد","kosten.briefing":"الملخص","kosten.sprache":"الإدخال الصوتي","kosten.uebersetzung":"الترجمات","kosten.tagesgericht":"طبق اليوم",
 "aktion.einkaufsliste":"أضف إلى قائمة المشتريات","aktion.bestand":"عرض المخزون","aktion.verlust":"عرض الملخص","aktion.einkauf":"افتح قائمة المشتريات","aktion.neu_scannen":"امسح الآن",
 "mhd.abgelaufen":"منتهي","mhd.heute":"اليوم","mhd.morgen":"غداً","mhd.tage":A("يوم واحد","يومان","{n} أيام","{n} يوماً"),"mhd.in_tagen":A("بعد يوم","بعد يومين","بعد {n} أيام","بعد {n} يوماً"),
 "mitarbeiter.hallo":"مرحباً، {name}","mitarbeiter.sprache_waehlen":"اختر اللغة","mitarbeiter.heute":"المسح اليوم","mitarbeiter.fortschritt":"تم {n} من {von}",
 "mitarbeiter.jetzt_dran":"الآن دورك","mitarbeiter.erledigt":"تم · {zeit}","mitarbeiter.offen":"مفتوح","mitarbeiter.bitte_bestaetigen":"أكّد من فضلك",
 "mitarbeiter.stellen":A("مكان تصوير واحد","مكانا تصوير","{n} أماكن تصوير","{n} مكان تصوير"),"mitarbeiter.dauer":A("حوالي دقيقة واحدة","حوالي دقيقتين","حوالي {n} دقائق","حوالي {n} دقيقة"),"mitarbeiter.scan_starten":"ابدأ المسح","mitarbeiter.etwas_weg":"هل رُمي شيء؟","tag.0":"الأحد","tag.1":"الاثنين","tag.2":"الثلاثاء","tag.3":"الأربعاء","tag.4":"الخميس","tag.5":"الجمعة","tag.6":"السبت","mitarbeiter.weggeworfen":"هدر","mitarbeiter.erinnerung":"تذكير على الهاتف الساعة {zeit}","mitarbeiter.erinnerung_an":"تفعيل","mitarbeiter.keine_bereiche":"لا توجد أقسام بعد","mitarbeiter.keine_bereiche_unter":"المدير يضيفها في الإعداد.",
 "monat.1":"يناير","monat.2":"فبراير","monat.3":"مارس","monat.4":"أبريل","monat.5":"مايو","monat.6":"يونيو","monat.7":"يوليو","monat.8":"أغسطس","monat.9":"سبتمبر","monat.10":"أكتوبر","monat.11":"نوفمبر","monat.12":"ديسمبر",
 "nav.titel":"التنقل الرئيسي","nav.assistent":"المساعد","nav.bestand":"المخزون","nav.einkauf":"المشتريات","nav.einkaufsliste":"قائمة المشتريات","nav.scannen":"امسح المخزن",
 "offline.kein_netz":"لا توجد شبكة. يمكنك المسح رغم ذلك.","offline.wird_hochgeladen":"سيُرفع عند توفر الشبكة","offline.titel":"محفوظ على الهاتف",
 "offline.wird_hochgeladen_lang":"لا توجد شبكة هنا. الصور آمنة على الهاتف وستُرفع عند توفر الشبكة وفتح التطبيق.",
 "offline.fehler":"فشل الرفع – اضغط لإعادة المحاولة",
 "rueckfrage.kurze_frage":"سؤال سريع","rueckfrage.wie_viele":"كم {einheit} من {produkt} هنا؟","rueckfrage.weiss_nicht":"لا أعرف",
 "scan.hinweis":"الرف كله في الصورة. عدة صور لا بأس.","scan.geist_hinweis":"وجّه الكاميرا حسب الصورة الباهتة.","scan.geist_aus":"إخفاء الصورة المساعدة","scan.geist_an":"إظهار الصورة المساعدة",
 "scan.lampe":"مصباح",
 "scan.zu_dunkel":"الصورة مظلمة جدًا. زد الإضاءة والتقط الصورة مرة أخرى.",
 "scan.zu_dunkel_lampe":"الصورة مظلمة جدًا. شغّل المصباح في الأعلى والتقط الصورة مرة أخرى.",
 "scan.kamera_app":"اضغط على الزر الدائري – ستفتح كاميرا الهاتف.",
 "bestaetigen.qualitaet_dunkel":"كانت إحدى الصور مظلمة جدًا – قد تكون الأعداد غير دقيقة.",
 "bestaetigen.qualitaet_unscharf":"كانت إحدى الصور غير واضحة – قد تكون الأعداد غير دقيقة.",
 "bestaetigen.qualitaet_zu_weit":"التُقطت إحدى الصور من بعيد جدًا – قد تكون الأعداد غير دقيقة.",
 "bestaetigen.qualitaet_verdeckt":"كانت بضاعة مغطاة في إحدى الصور – قد تكون الأعداد غير دقيقة.",
 "bestaetigen.qualitaet_spiegelung":"كان في إحدى الصور انعكاس – قد تكون الأعداد غير دقيقة.",
 "bestaetigen.unbekannt":"غير موجود في الكتالوج: {liste}. هل يجب عدّه؟ أضفه في الأسفل عبر „{knopf}“.",
 "scan.foto":"التقط صورة","scan.fotos":A("صورة واحدة","صورتان","{n} صور","{n} صورة"),"scan.letztes_weg":"احذف آخر صورة","scan.fertig":"تم","scan.naechste":"المكان التالي",
 "scan.schaue_an":"دعني أنظر …","scan.erkennen_fehler":"لم ينجح التعرّف.","scan.liegt_auf_geraet":"لا تقلق: الصور على الهاتف.",
 "scan.kamera_verweigert":"الكاميرا غير مسموح بها. اسمح بها في إعدادات الهاتف.","scan.kamera_fehler":"الكاميرا لا تعمل.",
 "splash.slogan":"مخزنك. دائماً أمام عينيك.",
 "sprache.willkommen":"أهلاً وسهلاً","sprache.frage":"بأي لغة تريد استخدام التطبيق؟","sprache.sprechen":"تحدّث","sprache.fertig":"انتهيت من الكلام",
 "sprache.wandelt":"أستمع …","sprache.nichts_verstanden":"لم أفهم. أعد من فضلك أو اكتب.",
 "team.titel":"الفريق","team.chef":"المدير","team.mitarbeiter":"موظف","team.einladen":"ادعُ موظفاً","team.code_ist":"الرمز هو","team.code_gueltig":"صالح 14 يوماً، لشخص واحد.",
 "team.per_whatsapp":"أرسل عبر واتساب","team.link_kopieren":"انسخ الرابط","team.kopiert":"تم النسخ.","team.entfernen":"إزالة","team.wirklich_entfernen":"هل تريد إزالة {name} فعلاً؟",
 "team.einladung_text":"مرحباً! أنت مدعو إلى {betrieb} في The Chef. افتح الرابط: {link} – أو أدخل الرمز {code}.",
 "verlust.wert":"قيمة الهدر","verlust.vergleich":"{betrag} مقارنة بـ{monat}","verlust.am_meisten":"الأكثر هدراً","verlust.tipp":"نصيحة من المساعد",
 "verlust.tipp_holen":"احصل على نصيحة","verlust.tipp_frage":"ما الذي هُدر أكثر هذا الشهر وماذا أستطيع أن أحسّن؟","verlust.ohne_preis":A("بلاغ بدون سعر لم يُحتسب","بلاغان بدون سعر لم يُحتسبا","{n} بلاغات بدون سعر لم تُحتسب","{n} بلاغاً بدون سعر لم يُحتسب"),
 "vorlage.kuehlhaus":"غرفة التبريد","vorlage.tiefkuehler":"المجمّد","vorlage.trocken":"المخزن الجاف",
 "vorschlag.bestellen":"ماذا يجب أن أطلب؟","vorschlag.haehnchen":"هل يكفي الدجاج لعطلة نهاية الأسبوع؟","vorschlag.weggeworfen":"كم هُدر؟","vorschlag.tagesgericht":"ماذا لطبق اليوم؟",
 "weg.offline":"حُفظ على الهاتف – سيُرفع عند توفر الشبكة.","weg.warten":A("بلاغ هدر واحد سيُرفع عند توفر الشبكة.","بلاغا هدر سيُرفعان عند توفر الشبكة.","{n} بلاغات هدر ستُرفع عند توفر الشبكة.","{n} بلاغ هدر سيُرفع عند توفر الشبكة."),"weg.fehler":"لم يصل بلاغ الهدر هذا: {produkt}، {menge}.","weg.verwerfen":"تجاهل","weg.frage":"ماذا رُمي؟","weg.wie_viel":"كم؟","weg.gespeichert":"تم الحفظ.",
 "zahl.tippen":"اكتب رقماً","zahl.sagen":"قل الرقم","zahl.oder_sagen":"أو قله","zahl.verstanden":"«{text}» ← {zahl}","zahl.nicht_verstanden":"«{text}» – لم يُفهم رقم. اكتب من فضلك.",
 "zeit.nie":"أبداً","zeit.heute":"اليوم","zeit.gestern":"أمس","zeit.heute_um":"اليوم، {zeit}","zeit.gestern_um":"أمس، {zeit}","zeit.vor_tagen":A("قبل يوم","قبل يومين","قبل {n} أيام","قبل {n} يوماً"),
}
json.dump(dict(sorted(t.items())), open('public/sprachen/ar.json','w'), ensure_ascii=False, indent=1)
print(len(t))
