import json
P=lambda one,other: {"one":one,"other":other}
de = {
 "allg.fertig":"Fertig","allg.gespeichert":"Gespeichert","allg.hinzufuegen":"Hinzufügen","allg.loeschen":"Löschen","allg.los":"Los geht's",
 "allg.mehr":"Mehr","allg.nochmal":"Nochmal versuchen","allg.schliessen":"Schließen","allg.senden":"Senden","allg.spaeter":"Später",
 "allg.speichern":"Speichern","allg.weiter":"Weiter","allg.weniger":"Weniger","allg.zurueck":"Zurück",
 "ampel.gut":"Alles gut","ampel.knapp":"Wird knapp","ampel.knapp_kurz":"knapp","ampel.sofort":"Sofort",
 "anmelden.titel":"Willkommen","anmelden.unter":"Wer bist du?","anmelden.ich_chef":"Ich bin der Chef","anmelden.ich_chef_unter":"Betrieb anlegen oder anmelden",
 "anmelden.ich_mitarbeiter":"Ich arbeite hier","anmelden.ich_mitarbeiter_unter":"Mit dem Code vom Chef","anmelden.anmelden":"Anmelden","anmelden.neu":"Neu hier",
 "anmelden.konto_anlegen":"Konto anlegen","anmelden.email":"E-Mail","anmelden.passwort":"Passwort (mind. 8 Zeichen)","anmelden.code":"Code vom Chef",
 "anmelden.dein_name":"Dein Vorname","anmelden.mail_bestaetigen":"Fast geschafft: Wir haben dir an {email} eine E-Mail geschickt. Bitte den Link darin antippen.",
 "anmelden.demo_hinweis":"Demo: Ohne Server, zum Anschauen. Die Erkennung ist simuliert.",
 "antwort.noch_da":"Noch da","antwort.brauchst":"Brauchst du","antwort.fehlt":"Fehlt",
 "assistent.morgen":"Guten Morgen","assistent.tag":"Guten Tag","assistent.abend":"Guten Abend",
 "assistent.gescannt":"Heute gescannt · {zeit} · {wer}","assistent.teilweise":"Heute {n} von {von} gescannt",
 "assistent.nicht_gescannt":"Heute nicht gescannt","assistent.es_fehlt":"Es fehlt: {bereiche}","assistent.zahlen_alt":"Die Zahlen sind vom letzten Scan: {wann}.",
 "assistent.selbst_scannen":"Jetzt scannen","assistent.briefing":"Abend-Briefing","assistent.stand_jetzt":"Stand jetzt","assistent.vorlesen":"Vorlesen",
 "assistent.zum_bestand":"Zum Bestand","assistent.wichtig":P("{n} Ding ist wichtig","{n} Dinge sind wichtig"),"assistent.hinweise":"Hinweise","assistent.tagesgericht":"Tagesgericht-Idee",
 "assistent.tagesgericht_fehler":"Gerade keine Idee abrufbar.","assistent.frag_mich":"Frag mich etwas …",
 "assistent.verworfen":"Das kann ich gerade nicht sicher sagen. Bitte neu scannen oder anders fragen.",
 "bestaetigen.titel":"Das habe ich erkannt","bestaetigen.unter":"Stimmt alles? Tippe auf eine Kachel zum Ändern.",
 "bestaetigen.test_titel":"Bitte selbst zählen","bestaetigen.test_unter":"Genauigkeits-Test: Tippe auf jede Kachel und gib ein, wie viele es wirklich sind.",
 "bestaetigen.nichts_erkannt":"Ich habe nichts aus dem Katalog erkannt. Füge es von Hand hinzu oder mach ein neues Foto.",
 "bestaetigen.unsicher":"unsicher","bestaetigen.von_hand":"dazu","bestaetigen.zaehlen":"zählen","bestaetigen.fehlt_etwas":"Fehlt etwas?",
 "bestaetigen.speichern":"Alles richtig – speichern","bestaetigen.noch_offen":P("Noch {n} zählen","Noch {n} zählen"),"bestaetigen.noch_foto":"Noch ein Foto machen",
 "bestaetigen.mhd":"Haltbar bis (falls auf dem Etikett)","bestaetigen.nicht_da":"Nicht da ({zahl})","bestaetigen.schon_gespeichert":"Dieser Scan ist schon gespeichert.",
 "bestand.titel":"Bestand","bestand.letzter_scan":"Letzter Scan: {wann}","bestand.ware_im_lager":"Ware im Lager","bestand.weggeworfen_monat":"Weggeworfen {monat}",
 "bestand.ohne_preis":P("{n} Produkt ohne Preis","{n} Produkte ohne Preis"),"bestand.ampel":"Ampel","bestand.laeuft_bald_ab":"Läuft bald ab",
 "bestand.mhd_berechnet":"geschätzt (kein Etikett)","bestand.alles":"Alles im Lager","bestand.scan":"Scan: {wann}","bestand.mindestens":"Mindestens: {menge}",
 "bestand.leer":"Noch keine Produkte im Katalog.","bestand.produkte_anlegen":"Produkte anlegen",
 "briefing.laeuft_ab":"{produkt} läuft {wann} ab.","briefing.abgelaufen":"{produkt} ist abgelaufen.","briefing.nichts_laeuft_ab":"Nichts läuft in den nächsten 2 Tagen ab.",
 "briefing.knapp":"{produkt} wird knapp.","briefing.bestellen":"{menge} bestellen","briefing.alles_da":"Alles über dem Mindestbestand.",
 "briefing.einkauf":"Morgen einkaufen:","briefing.artikel":P("{n} Artikel","{n} Artikel"),
 "demo.bestand_satz":"{produkt}: {menge} da.","demo.einkauf_satz":P("{n} Artikel musst du bestellen.","{n} Artikel musst du bestellen."),
 "demo.reicht_ja":"Ja, das reicht.","demo.reicht_nein":"Nein, es fehlen etwa {menge}.","demo.zu_wenig_daten":"Dafür habe ich noch zu wenige Scans. Nach ein paar Tagen kann ich es schätzen.",
 "demo.quelle_bestand":"Aus deinem letzten Scan.","demo.quelle_verbrauch":"Geschätzt aus deinen Scans der letzten {tage} Tage.","demo.quelle_weg":"Aus den Weggeworfen-Meldungen.",
 "demo.weg_satz":"{betrag} diesen Monat.","demo.unbekannt":"Im Demo-Modus verstehe ich nur: bestellen, „Wie viel … haben wir?“, „Reicht …?“ und weggeworfen.",
 "demo.tagesgericht":"Teller mit {produkt}.","demo.tagesgericht_grund":"Verbraucht {produkt}, das bald abläuft.",
 "einheit.kiste":P("Kiste","Kisten"),"einheit.packung":P("Packung","Packungen"),"einheit.stueck":P("Stück","Stück"),"einheit.becher":P("Becher","Becher"),
 "einheit.beutel":P("Beutel","Beutel"),"einheit.flasche":P("Flasche","Flaschen"),"einheit.dose":P("Dose","Dosen"),"einheit.eimer":P("Eimer","Eimer"),
 "einheit.sack":P("Sack","Säcke"),"einheit.karton":P("Karton","Kartons"),"einheit.glas":P("Glas","Gläser"),"einheit.netz":P("Netz","Netze"),
 "einheit.spiess":P("Spieß","Spieße"),"einheit.kg":P("kg","kg"),"einheit.l":P("l","l"),
 "einkauf.titel":"Einkauf für morgen","einkauf.erstellt":"Vom Assistenten erstellt · Stand: {wann}","einkauf.muessen":P("Artikel muss nachbestellt werden","Artikel müssen nachbestellt werden"),
 "einkauf.nichts":"Nichts zu bestellen. Alles über dem Mindestbestand.","einkauf.noch_da":"Noch da: {menge}","einkauf.laeuft_ab":"Läuft heute ab",
 "einkauf.email":"E-Mail","einkauf.teilen_titel":"Einkauf für {datum}:","einkauf.anzahl":P("{n} Artikel","{n} Artikel"),
 "einrichtung.schritt":"Schritt {n} von {von}","einrichtung.betrieb_titel":"Dein Betrieb","einrichtung.betrieb_name":"Name des Betriebs",
 "einrichtung.bereiche_titel":"Bereiche & Foto-Stellen","einrichtung.produkte_titel":"Produkte","einrichtung.team_titel":"Mitarbeiter einladen",
 "einrichtung.iphone_titel":"Aufs Handy legen","einrichtung.fertig":"Fertig – los geht's",
 "einstellungen.titel":"Einstellungen","einstellungen.modus":"Modus","einstellungen.hell":"Hell","einstellungen.dunkel":"Dunkel","einstellungen.auto":"Automatisch",
 "einstellungen.akzent":"Akzentfarbe","einstellungen.akzent_warum":"Grün, Gelb und Rot gibt es nicht als Akzent – das sind die Ampelfarben.",
 "einstellungen.glas":"Glas","einstellungen.klar":"Klar","einstellungen.getoent":"Getönt","einstellungen.bewegung":"Bewegungen","einstellungen.bewegung_unter":"Kurze Animationen beim Öffnen",
 "einstellungen.sprache":"Sprache","einstellungen.push":"Mitteilungen","einstellungen.push_unter":"Wichtiges und das Abend-Briefing aufs Handy",
 "einstellungen.betrieb":"Betrieb","einstellungen.erinnerung":"Scan-Erinnerung für die Mitarbeiter","einstellungen.loeschfrist":"Scan-Fotos löschen nach",
 "einstellungen.tage":P("{n} Tag","{n} Tagen"),"einstellungen.loeschfrist_warum":"Auf Fotos können Mitarbeiter zu sehen sein. Die erkannten Zahlen bleiben.",
 "einstellungen.test":"Genauigkeits-Test","einstellungen.test_unter":"Mitarbeiter zählen selbst, ohne die Zahl der KI zu sehen",
 "einstellungen.abmelden":"Abmelden","einstellungen.demo_reset":"Demo zurücksetzen",
 "akzent.blau":"Blau","akzent.lila":"Lila","akzent.petrol":"Petrol",
 "fehler.unbekannt":"Etwas ist schiefgegangen.","fehler.verbindung":"Keine Verbindung zum Server.","fehler.laden":"Konnte nicht geladen werden.",
 "fehler.speichern":"Konnte nicht gespeichert werden.","fehler.nicht_angemeldet":"Bitte neu anmelden.","fehler.server":"Der Server hat einen Fehler gemeldet.",
 "fehler.foto":"Foto konnte nicht hochgeladen werden.","fehler.anmelden":"Anmelden hat nicht geklappt. E-Mail und Passwort prüfen.",
 "fehler.registrieren":"Konto konnte nicht angelegt werden.","fehler.beitreten":"Beitreten hat nicht geklappt.","fehler.code_ungueltig":"Der Code stimmt nicht oder wurde schon benutzt.",
 "fehler.sprache":"Sprache konnte nicht umgewandelt werden. Bitte tippen.","fehler.sprache_demo":"Spracheingabe braucht den Server – in der Demo bitte tippen.",
 "fehler.demo":"In der Demo nicht möglich.","fehler.keine_kamera":"Dieses Gerät hat keine Kamera für den Browser.","fehler.kein_mikrofon":"Mikrofon nicht verfügbar. Bitte tippen.",
 "fehler.push_ios_installieren":"Auf dem iPhone gehen Mitteilungen nur, wenn die App auf dem Home-Bildschirm liegt.","fehler.push_nicht_moeglich":"Dieses Gerät kann keine Mitteilungen.",
 "fehler.push_abgelehnt":"Mitteilungen wurden abgelehnt. In den Einstellungen des Handys erlauben.","fehler.push_nicht_eingerichtet":"Mitteilungen sind auf dem Server noch nicht eingerichtet.",
 "genauigkeit.titel":"Genauigkeit der Erkennung","genauigkeit.erklaerung":"Erkannt von der KI im Vergleich zu dem, was beim Bestätigen gezählt wurde. Letzte 30 Tage.",
 "genauigkeit.keine_daten":"Noch keine bestätigten Scans.","genauigkeit.genau":"Genau richtig","genauigkeit.gezaehlt":"Gezählt","genauigkeit.uebersehen":"Übersehen",
 "genauigkeit.zeile":"{genau} von {n} genau · Ø {abw} daneben",
 "gespeichert.titel":"Gespeichert.","gespeichert.danke":"Danke, {name}. Der Chef sieht jetzt alles.","gespeichert.zusammenfassung":P("{n} Produkt · {bereich} · {zeit}","{n} Produkte · {bereich} · {zeit}"),
 "gespeichert.als_naechstes":"Als Nächstes: {bereich}","gespeichert.weiter_scannen":"Weiter scannen","gespeichert.fertig_heute":"Fertig für heute","gespeichert.alles_fertig":"Alle Bereiche für heute erledigt.",
 "gespraech.leer":"Frag mich etwas zum Lager – per Text oder Mikrofon.","gespraech.auf_liste":"Auf der Einkaufsliste.","gespraech.daten_alt":"Die Daten sind alt – bitte neu scannen.",
 "gespraech.schaetzung":"Schätzung","gespraech.stand":"Stand: Scan {wann}.","gespraech.verworfen_warum":"Eine Zahl in meiner Antwort stand nicht in deinen Daten – deshalb habe ich sie nicht gezeigt.",
 "hinweis.abgelaufen":"{produkt} ist abgelaufen.","hinweis.laeuft_ab":"{produkt} läuft {wann} ab.","hinweis.leer":"{produkt} ist leer.","hinweis.knapp":"{produkt} wird knapp.",
 "hinweis.bestellen":"{menge} bestellen","hinweis.fehlen":"Es fehlen {menge}.","hinweis.nicht_gescannt":"Heute nicht gescannt.","hinweis.zur_liste":"Auf Einkaufsliste","hinweis.erledigt":"Erledigt",
 "installieren.titel":"App aufs Handy legen","installieren.schon":"Die App liegt schon auf dem Home-Bildschirm.",
 "installieren.warum_ios":"Auf dem iPhone kommen Mitteilungen nur an, wenn die App auf dem Home-Bildschirm liegt. So geht's in Safari:",
 "installieren.warum":"So legst du die App auf den Home-Bildschirm:","installieren.ios_1":"Unten auf „Teilen“ tippen (Kasten mit Pfeil nach oben).",
 "installieren.ios_2":"„Zum Home-Bildschirm“ wählen.","installieren.ios_3":"Oben rechts „Hinzufügen“ tippen.","installieren.ios_4":"The Chef ab jetzt über das Symbol öffnen.",
 "installieren.andere_1":"Oben rechts das Menü (⋮) öffnen.","installieren.andere_2":"„App installieren“ oder „Zum Startbildschirm“ wählen.",
 "katalog.bereiche":"Bereiche & Foto-Stellen","katalog.produkte":"Produkte","katalog.bereiche_erklaerung":"Bereiche sind die Orte, die jeden Tag gescannt werden. Pro Bereich legst du feste Foto-Stellen an – immer gleich fotografiert heißt genauer gezählt.",
 "katalog.positionen":"Foto-Stellen","katalog.position":"Foto-Stelle","katalog.position_neu":"Foto-Stelle hinzufügen","katalog.mit_foto":"mit Referenzfoto","katalog.ohne_foto":"noch ohne Referenzfoto",
 "katalog.bereich_neu":"Bereich hinzufügen","katalog.eigener_bereich":"Eigener Name …","katalog.referenzfoto":"Referenzfoto machen",
 "katalog.referenzfoto_erklaerung":"Einmal so fotografieren, wie später jeden Tag. Das Foto erscheint beim Scannen halb durchsichtig als Hilfe.",
 "katalog.wirklich_loeschen":"Wirklich löschen? Der Verlauf bleibt erhalten.","katalog.name":"Name","katalog.uebersetzen":"Andere Sprachen vorschlagen","katalog.vorschlag":"Vorschlag – bitte prüfen",
 "katalog.produkte_erklaerung":"Jedes Produkt einmal fotografieren und festlegen, wie es gezählt wird. Die KI zählt nur Einheiten und rechnet selbst um.",
 "katalog.produkt_neu":"Produkt hinzufügen","katalog.noch_keine":"Noch keine Produkte.","katalog.foto":"Produktfoto","katalog.foto_warum":"Hilft der KI beim Erkennen.",
 "katalog.kategorie":"Art","katalog.wie_zaehlen":"Wie wird gezählt?","katalog.wie_zaehlen_unter":"Was sieht man im Regal? Die Kiste, den Becher, das Stück …",
 "katalog.zaehleinheit":"Einheit im Regal","katalog.inhalt":"Inhalt pro Einheit (optional)","katalog.basiseinheit":"in","katalog.beispiel":"1 {einheit} = {menge} {basis}",
 "katalog.mindestbestand":"Mindestens ({einheit})","katalog.haltbarkeit":"Haltbar (Tage)","katalog.preis":"Preis pro {einheit} in € (optional)","katalog.wo":"Wo liegt es?",
 "kategorie.fleisch":"Fleisch","kategorie.fisch":"Fisch","kategorie.gemuese":"Gemüse","kategorie.obst":"Obst","kategorie.milch":"Milchprodukte","kategorie.brot":"Brot & Teig",
 "kategorie.tiefkuehl":"Tiefkühlware","kategorie.trocken":"Trockenware","kategorie.getraenke":"Getränke","kategorie.sonstiges":"Sonstiges",
 "kosten.titel":"KI-Kosten","kosten.letzte_30":"Letzte 30 Tage","kosten.zeile":P("{n} Aufruf · Ø {je} · Ø {tokens} Tokens","{n} Aufrufe · Ø {je} · Ø {tokens} Tokens"),
 "kosten.keine":"Noch keine Kosten.","kosten.je_betrieb":"Je Betrieb","kosten.hinweis":"Umgerechnet mit festem Kurs aus US-Dollar. Die Rechnung von Anthropic ist maßgeblich.",
 "kosten.scan":"Scan-Erkennung","kosten.assistent":"Assistent","kosten.briefing":"Briefing","kosten.sprache":"Spracheingabe","kosten.uebersetzung":"Übersetzungen","kosten.tagesgericht":"Tagesgericht",
 "aktion.einkaufsliste":"Auf Einkaufsliste","aktion.bestand":"Bestand ansehen","aktion.verlust":"Übersicht ansehen","aktion.einkauf":"Einkaufsliste öffnen","aktion.neu_scannen":"Jetzt scannen",
 "mhd.abgelaufen":"abgelaufen","mhd.heute":"heute","mhd.morgen":"morgen","mhd.tage":P("{n} Tag","{n} Tage"),"mhd.in_tagen":P("in {n} Tag","in {n} Tagen"),
 "mitarbeiter.hallo":"Hallo, {name}","mitarbeiter.sprache_waehlen":"Sprache wählen","mitarbeiter.heute":"Heute scannen","mitarbeiter.fortschritt":"{n} von {von} erledigt",
 "mitarbeiter.jetzt_dran":"Jetzt dran","mitarbeiter.erledigt":"Erledigt · {zeit}","mitarbeiter.offen":"Offen","mitarbeiter.bitte_bestaetigen":"Bitte bestätigen",
 "mitarbeiter.weggeworfen":"Weggeworfen","mitarbeiter.erinnerung":"Erinnerung um {zeit} aufs Handy","mitarbeiter.erinnerung_an":"Einschalten","mitarbeiter.keine_bereiche":"Noch keine Bereiche","mitarbeiter.keine_bereiche_unter":"Der Chef legt sie in der Einrichtung an.",
 "monat.1":"Januar","monat.2":"Februar","monat.3":"März","monat.4":"April","monat.5":"Mai","monat.6":"Juni","monat.7":"Juli","monat.8":"August","monat.9":"September","monat.10":"Oktober","monat.11":"November","monat.12":"Dezember",
 "nav.titel":"Hauptnavigation","nav.assistent":"Assistent","nav.bestand":"Bestand","nav.einkauf":"Einkauf","nav.einkaufsliste":"Einkaufsliste","nav.scannen":"Lager scannen",
 "offline.kein_netz":"Kein Netz. Du kannst trotzdem scannen.","offline.wird_hochgeladen":"Wird hochgeladen, sobald Netz da ist","offline.titel":"Auf dem Handy gespeichert",
 "offline.wird_hochgeladen_lang":"Kein Netz hier. Die Fotos sind sicher auf dem Handy und werden hochgeladen, sobald Netz da ist und die App offen ist.",
 "offline.fehler":"Hochladen hat nicht geklappt – antippen zum Wiederholen",
 "rueckfrage.kurze_frage":"Kurze Frage","rueckfrage.wie_viele":"Wie viele {einheit} {produkt} sind das?","rueckfrage.weiss_nicht":"Weiß ich nicht",
 "scan.hinweis":"Ganzes Regal ins Bild. Mehrere Fotos sind okay.","scan.geist_hinweis":"Kamera am hellen Bild ausrichten.","scan.geist_aus":"Hilfsbild aus","scan.geist_an":"Hilfsbild an",
 "scan.lampe":"Taschenlampe","scan.foto":"Foto aufnehmen","scan.fotos":P("{n} Foto","{n} Fotos"),"scan.letztes_weg":"Letztes Foto löschen","scan.fertig":"Fertig","scan.naechste":"Nächste Stelle",
 "scan.schaue_an":"Ich schaue mir das an …","scan.erkennen_fehler":"Die Erkennung hat nicht geklappt.","scan.liegt_auf_geraet":"Keine Sorge: Die Fotos liegen auf dem Handy.",
 "scan.kamera_verweigert":"Die Kamera ist nicht erlaubt. Bitte in den Einstellungen des Handys erlauben.","scan.kamera_fehler":"Die Kamera startet nicht.",
 "splash.slogan":"Dein Lager. Immer im Blick.",
 "sprache.willkommen":"Willkommen","sprache.frage":"In welcher Sprache möchtest du die App nutzen?","sprache.sprechen":"Sprechen","sprache.fertig":"Fertig gesprochen",
 "sprache.wandelt":"Ich höre …","sprache.nichts_verstanden":"Nichts verstanden. Bitte nochmal oder tippen.",
 "team.titel":"Team","team.chef":"Chef","team.mitarbeiter":"Mitarbeiter","team.einladen":"Mitarbeiter einladen","team.code_ist":"Der Code ist","team.code_gueltig":"14 Tage gültig, für eine Person.",
 "team.per_whatsapp":"Per WhatsApp schicken","team.link_kopieren":"Link kopieren","team.kopiert":"Kopiert.","team.entfernen":"Entfernen","team.wirklich_entfernen":"{name} wirklich entfernen?",
 "team.einladung_text":"Hallo! Du bist bei {betrieb} in The Chef eingeladen. Öffne den Link: {link} – oder gib den Code {code} ein.",
 "verlust.wert":"Wert weggeworfen","verlust.vergleich":"{betrag} zum {monat}","verlust.am_meisten":"Am meisten weggeworfen","verlust.tipp":"Tipp vom Assistenten",
 "verlust.tipp_holen":"Tipp holen","verlust.tipp_frage":"Was wurde diesen Monat am meisten weggeworfen und was kann ich besser machen?","verlust.ohne_preis":P("{n} Meldung ohne Preis nicht mitgezählt","{n} Meldungen ohne Preis nicht mitgezählt"),
 "vorlage.kuehlhaus":"Kühlhaus","vorlage.tiefkuehler":"Tiefkühler","vorlage.trocken":"Trockenlager",
 "vorschlag.bestellen":"Was muss ich bestellen?","vorschlag.haehnchen":"Reicht das Hähnchen fürs Wochenende?","vorschlag.weggeworfen":"Wie viel weggeworfen?","vorschlag.tagesgericht":"Was als Tagesgericht?",
 "weg.frage":"Was wurde weggeworfen?","weg.wie_viel":"Wie viel?","weg.gespeichert":"Gespeichert.",
 "zahl.tippen":"Zahl eintippen","zahl.sagen":"Zahl sagen","zahl.oder_sagen":"oder sagen","zahl.verstanden":"„{text}“ → {zahl}","zahl.nicht_verstanden":"„{text}“ – keine Zahl erkannt. Bitte tippen.",
 "zeit.nie":"noch nie","zeit.heute":"heute","zeit.gestern":"gestern","zeit.heute_um":"heute, {zeit}","zeit.gestern_um":"gestern, {zeit}","zeit.vor_tagen":P("vor {n} Tag","vor {n} Tagen"),
}
json.dump(dict(sorted(de.items())), open('public/sprachen/de.json','w'), ensure_ascii=False, indent=1)
print(len(de))
