import json
P=lambda one,other: {"one":one,"other":other}
t = {
 "allg.fertig":"Done","allg.gespeichert":"Saved","allg.hinzufuegen":"Add","allg.loeschen":"Delete","allg.los":"Let's go","allg.mehr":"More","allg.nochmal":"Try again",
 "allg.schliessen":"Close","allg.senden":"Send","allg.spaeter":"Later","allg.speichern":"Save","allg.weiter":"Continue","allg.weniger":"Less","allg.zurueck":"Back",
 "ampel.gut":"All good","ampel.knapp":"Running low","ampel.knapp_kurz":"low","ampel.sofort":"Urgent",
 "anmelden.titel":"Welcome","anmelden.unter":"Who are you?","anmelden.ich_chef":"I'm the boss","anmelden.ich_chef_unter":"Create a business or sign in",
 "anmelden.ich_mitarbeiter":"I work here","anmelden.ich_mitarbeiter_unter":"With the code from your boss","anmelden.anmelden":"Sign in","anmelden.neu":"New here",
 "anmelden.konto_anlegen":"Create account","anmelden.email":"Email","anmelden.passwort":"Password (at least 8 characters)","anmelden.code":"Code from your boss",
 "anmelden.dein_name":"Your first name","anmelden.mail_bestaetigen":"Almost there: we sent an email to {email}. Please tap the link in it.",
 "anmelden.demo_hinweis":"Demo: no server, just to look around. Recognition is simulated.",
 "antwort.noch_da":"In stock","antwort.brauchst":"You need","antwort.fehlt":"Missing",
 "assistent.morgen":"Good morning","assistent.tag":"Good afternoon","assistent.abend":"Good evening",
 "assistent.gescannt":"Scanned today · {zeit} · {wer}","assistent.teilweise":"Today {n} of {von} scanned",
 "assistent.nicht_gescannt":"Not scanned today","assistent.es_fehlt":"Missing: {bereiche}","assistent.zahlen_alt":"The numbers are from the last scan: {wann}.",
 "assistent.selbst_scannen":"Scan now","assistent.briefing":"Evening briefing","assistent.stand_jetzt":"Right now","assistent.vorlesen":"Read aloud",
 "assistent.zum_bestand":"To stock","assistent.wichtig":P("{n} thing matters","{n} things matter"),"assistent.hinweise":"Notices","assistent.tagesgericht":"Dish of the day idea",
 "assistent.tagesgericht_fehler":"No idea available right now.","assistent.frag_mich":"Ask me something …",
 "assistent.verworfen":"I can't say that for sure right now. Please scan again or ask differently.",
 "bestaetigen.titel":"This is what I found","bestaetigen.unter":"All correct? Tap a tile to change it.",
 "bestaetigen.test_titel":"Please count yourself","bestaetigen.test_unter":"Accuracy test: tap each tile and enter how many there really are.",
 "bestaetigen.nichts_erkannt":"I didn't recognise anything from the catalogue. Add it by hand or take a new photo.",
 "bestaetigen.unsicher":"unsure","bestaetigen.von_hand":"added","bestaetigen.zaehlen":"count","bestaetigen.fehlt_etwas":"Something missing?",
 "bestaetigen.speichern":"All correct – save","bestaetigen.noch_offen":P("{n} left to count","{n} left to count"),"bestaetigen.noch_foto":"Take another photo",
 "bestaetigen.mhd":"Best before (if on the label)","bestaetigen.nicht_da":"Not there ({zahl})","bestaetigen.schon_gespeichert":"This scan is already saved.",
 "bestand.titel":"Stock","bestand.letzter_scan":"Last scan: {wann}","bestand.ware_im_lager":"Goods in stock","bestand.weggeworfen_monat":"Thrown away {monat}",
 "bestand.ohne_preis":P("{n} product without price","{n} products without price"),"bestand.ampel":"Traffic light","bestand.laeuft_bald_ab":"Expiring soon",
 "bestand.mhd_berechnet":"estimated (no label)","bestand.alles":"Everything in stock","bestand.scan":"Scan: {wann}","bestand.mindestens":"Minimum: {menge}",
 "bestand.leer":"No products in the catalogue yet.","bestand.produkte_anlegen":"Add products",
 "briefing.laeuft_ab":"{produkt} expires {wann}.","briefing.abgelaufen":"{produkt} has expired.","briefing.nichts_laeuft_ab":"Nothing expires in the next 2 days.",
 "briefing.knapp":"{produkt} is running low.","briefing.bestellen":"order {menge}","briefing.alles_da":"Everything above minimum stock.",
 "briefing.einkauf":"Shopping tomorrow:","briefing.artikel":P("{n} item","{n} items"),
 "demo.bestand_satz":"{produkt}: {menge} in stock.","demo.einkauf_satz":P("You need to order {n} item.","You need to order {n} items."),
 "demo.reicht_ja":"Yes, that's enough.","demo.reicht_nein":"No, about {menge} are missing.","demo.zu_wenig_daten":"I don't have enough scans for that yet. After a few days I can estimate it.",
 "demo.quelle_bestand":"From your last scan.","demo.quelle_verbrauch":"Estimated from your scans of the last {tage} days.","demo.quelle_weg":"From the thrown-away reports.",
 "demo.weg_satz":"{betrag} this month.","demo.unbekannt":"In demo mode I only understand: order, “How much … do we have?”, “Is there enough …?” and thrown away.",
 "demo.tagesgericht":"Plate with {produkt}.","demo.tagesgericht_grund":"Uses up {produkt}, which expires soon.",
 "einheit.kiste":P("crate","crates"),"einheit.packung":P("pack","packs"),"einheit.stueck":P("piece","pieces"),"einheit.becher":P("tub","tubs"),
 "einheit.beutel":P("bag","bags"),"einheit.flasche":P("bottle","bottles"),"einheit.dose":P("can","cans"),"einheit.eimer":P("bucket","buckets"),
 "einheit.sack":P("sack","sacks"),"einheit.karton":P("box","boxes"),"einheit.glas":P("jar","jars"),"einheit.netz":P("net","nets"),
 "einheit.spiess":P("cone","cones"),"einheit.kg":P("kg","kg"),"einheit.l":P("l","l"),
 "einkauf.titel":"Shopping for tomorrow","einkauf.erstellt":"Made by the assistant · as of: {wann}","einkauf.muessen":P("item needs to be reordered","items need to be reordered"),
 "einkauf.nichts":"Nothing to order. Everything above minimum stock.","einkauf.noch_da":"In stock: {menge}","einkauf.laeuft_ab":"Expires today",
 "einkauf.email":"Email","einkauf.teilen_titel":"Shopping for {datum}:","einkauf.anzahl":P("{n} item","{n} items"),
 "einrichtung.schritt":"Step {n} of {von}","einrichtung.betrieb_titel":"Your business","einrichtung.betrieb_name":"Name of the business",
 "einrichtung.bereiche_titel":"Areas & photo spots","einrichtung.produkte_titel":"Products","einrichtung.team_titel":"Invite staff",
 "einrichtung.iphone_titel":"Put it on your phone","einrichtung.fertig":"Done – let's go",
 "einstellungen.titel":"Settings","einstellungen.modus":"Mode","einstellungen.hell":"Light","einstellungen.dunkel":"Dark","einstellungen.auto":"Automatic",
 "einstellungen.akzent":"Accent colour","einstellungen.akzent_warum":"Green, yellow and red aren't offered as accents – they are the traffic-light colours.",
 "einstellungen.glas":"Glass","einstellungen.klar":"Clear","einstellungen.getoent":"Tinted","einstellungen.bewegung":"Motion","einstellungen.bewegung_unter":"Short animations when opening",
 "einstellungen.sprache":"Language","einstellungen.push":"Notifications","einstellungen.push_unter":"Important things and the evening briefing on your phone",
 "einstellungen.betrieb":"Business","einstellungen.erinnerung":"Scan reminder for staff","einstellungen.loeschfrist":"Delete scan photos after",
 "einstellungen.tage":P("{n} day","{n} days"),"einstellungen.loeschfrist_warum":"Staff may be visible in photos. The recognised numbers stay.",
 "einstellungen.test":"Accuracy test","einstellungen.test_unter":"Staff count themselves without seeing the AI's number",
 "einstellungen.abmelden":"Sign out","einstellungen.demo_reset":"Reset demo",
 "akzent.blau":"Blue","akzent.lila":"Purple","akzent.petrol":"Teal",
 "fehler.unbekannt":"Something went wrong.","fehler.verbindung":"No connection to the server.","fehler.laden":"Couldn't be loaded.",
 "fehler.speichern":"Couldn't be saved.","fehler.nicht_angemeldet":"Please sign in again.","fehler.server":"The server reported an error.",
 "fehler.foto":"Photo couldn't be uploaded.","fehler.anmelden":"Sign-in didn't work. Check email and password.",
 "fehler.registrieren":"Account couldn't be created.","fehler.beitreten":"Joining didn't work.","fehler.code_ungueltig":"The code is wrong or already used.",
 "fehler.sprache":"Couldn't convert speech. Please type.","fehler.sprache_demo":"Voice input needs the server – please type in the demo.",
 "fehler.demo":"Not possible in the demo.","fehler.keine_kamera":"This device has no camera for the browser.","fehler.kein_mikrofon":"Microphone not available. Please type.",
 "fehler.push_ios_installieren":"On iPhone, notifications only work when the app is on the home screen.","fehler.push_nicht_moeglich":"This device can't receive notifications.",
 "fehler.push_ios_faehigkeit":"Notifications aren't switched on in this app version yet. The boss sets this up once in Xcode.","fehler.push_abgelehnt":"Notifications were declined. Allow them in the phone settings.","fehler.push_nicht_eingerichtet":"Notifications aren't set up on the server yet.",
 "genauigkeit.titel":"Recognition accuracy","genauigkeit.erklaerung":"Recognised by the AI compared with what was counted when confirming. Last 30 days.",
 "genauigkeit.keine_daten":"No confirmed scans yet.","genauigkeit.genau":"Exactly right","genauigkeit.gezaehlt":"Counted","genauigkeit.uebersehen":"Missed",
 "genauigkeit.zeile":"{genau} of {n} exact · off by {abw} on average",
 "gespeichert.titel":"Saved.","gespeichert.danke":"Thanks, {name}. The boss can see everything now.","gespeichert.zusammenfassung":P("{n} product · {bereich} · {zeit}","{n} products · {bereich} · {zeit}"),
 "gespeichert.als_naechstes":"Next: {bereich}","gespeichert.weiter_scannen":"Keep scanning","gespeichert.fertig_heute":"Done for today","gespeichert.alles_fertig":"All areas done for today.",
 "gespraech.leer":"Ask me something about the stock – by text or microphone.","gespraech.auf_liste":"On the shopping list.","gespraech.daten_alt":"The data is old – please scan again.",
 "gespraech.schaetzung":"Estimate","gespraech.stand":"As of: scan {wann}.","gespraech.verworfen_warum":"A number in my answer wasn't in your data – so I didn't show it.",
 "hinweis.abgelaufen":"{produkt} has expired.","hinweis.laeuft_ab":"{produkt} expires {wann}.","hinweis.leer":"{produkt} is empty.","hinweis.knapp":"{produkt} is running low.",
 "hinweis.bestellen":"order {menge}","hinweis.fehlen":"{menge} missing.","hinweis.nicht_gescannt":"Not scanned today.","hinweis.zur_liste":"To shopping list","hinweis.erledigt":"Done",
 "installieren.titel":"Put the app on your phone","installieren.schon":"The app is already on the home screen.",
 "installieren.warum_ios":"On iPhone, notifications only arrive when the app is on the home screen. Here's how in Safari:",
 "installieren.warum":"How to put the app on the home screen:","installieren.ios_1":"Tap “Share” at the bottom (box with an arrow up).",
 "installieren.ios_2":"Choose “Add to Home Screen”.","installieren.ios_3":"Tap “Add” at the top right.","installieren.ios_4":"From now on, open The Chef from the icon.",
 "installieren.andere_1":"Open the menu (⋮) at the top right.","installieren.andere_2":"Choose “Install app” or “Add to Home screen”.",
 "katalog.bereiche":"Areas & photo spots","katalog.produkte":"Products","katalog.bereiche_erklaerung":"Areas are the places scanned every day. For each area you set fixed photo spots – photographed the same way every time means counted more accurately.",
 "katalog.mindest_vorschlag":"Suggestion from the scans: {menge}. Usage about {pro_tag} per day (last {tage} days) – lasts {reichweite} days.","katalog.mindest_zu_wenig":"A suggestion appears after a few days of scans.","katalog.uebernehmen":"Use it","katalog.positionen":"Photo spots","katalog.position":"Photo spot","katalog.position_neu":"Add photo spot","katalog.mit_foto":"with reference photo","katalog.ohne_foto":"no reference photo yet",
 "katalog.bereich_neu":"Add area","katalog.eigener_bereich":"Own name …","katalog.referenzfoto":"Take reference photo",
 "katalog.referenzfoto_erklaerung":"Photograph it once the way you will every day. The photo appears half-transparent as a guide when scanning.",
 "katalog.wirklich_loeschen":"Really delete? The history is kept.","katalog.name":"Name","katalog.uebersetzen":"Suggest other languages","katalog.vorschlag":"Suggestion – please check",
 "katalog.produkte_erklaerung":"Photograph each product once and set how it is counted. The AI only counts units and converts by itself.",
 "katalog.produkt_neu":"Add product","katalog.noch_keine":"No products yet.","katalog.foto":"Product photo","katalog.foto_warum":"Helps the AI recognise it.",
 "katalog.kategorie":"Type","katalog.wie_zaehlen":"How is it counted?","katalog.wie_zaehlen_unter":"What do you see on the shelf? The crate, the tub, the piece …",
 "katalog.zaehleinheit":"Unit on the shelf","katalog.inhalt":"Content per unit (optional)","katalog.basiseinheit":"in","katalog.beispiel":"1 {einheit} = {menge} {basis}",
 "katalog.mindestbestand":"Minimum ({einheit})","katalog.haltbarkeit":"Keeps (days)","katalog.preis":"Price per {einheit} in € (optional)","katalog.wo":"Where is it kept?",
 "kategorie.fleisch":"Meat","kategorie.fisch":"Fish","kategorie.gemuese":"Vegetables","kategorie.obst":"Fruit","kategorie.milch":"Dairy","kategorie.brot":"Bread & dough",
 "kategorie.tiefkuehl":"Frozen","kategorie.trocken":"Dry goods","kategorie.getraenke":"Drinks","kategorie.sonstiges":"Other",
 "kosten.titel":"AI costs","kosten.letzte_30":"Last 30 days","kosten.zeile":P("{n} call · avg {je} · avg {tokens} tokens","{n} calls · avg {je} · avg {tokens} tokens"),
 "kosten.keine":"No costs yet.","kosten.je_betrieb":"Per business","kosten.hinweis":"Converted from US dollars at a fixed rate. Anthropic's invoice is what counts.",
 "kosten.scan":"Scan recognition","kosten.assistent":"Assistant","kosten.briefing":"Briefing","kosten.sprache":"Voice input","kosten.uebersetzung":"Translations","kosten.tagesgericht":"Dish of the day",
 "aktion.einkaufsliste":"Add to shopping list","aktion.bestand":"View stock","aktion.verlust":"View overview","aktion.einkauf":"Open shopping list","aktion.neu_scannen":"Scan now",
 "mhd.abgelaufen":"expired","mhd.heute":"today","mhd.morgen":"tomorrow","mhd.tage":P("{n} day","{n} days"),"mhd.in_tagen":P("in {n} day","in {n} days"),
 "mitarbeiter.hallo":"Hi, {name}","mitarbeiter.sprache_waehlen":"Choose language","mitarbeiter.heute":"Scan today","mitarbeiter.fortschritt":"{n} of {von} done",
 "mitarbeiter.jetzt_dran":"Up next","mitarbeiter.erledigt":"Done · {zeit}","mitarbeiter.offen":"Open","mitarbeiter.bitte_bestaetigen":"Please confirm",
 "mitarbeiter.stellen":P("{n} photo spot","{n} photo spots"),"mitarbeiter.dauer":P("about {n} minute","about {n} minutes"),"mitarbeiter.scan_starten":"Start scan","mitarbeiter.etwas_weg":"Threw something away?","tag.0":"Sunday","tag.1":"Monday","tag.2":"Tuesday","tag.3":"Wednesday","tag.4":"Thursday","tag.5":"Friday","tag.6":"Saturday","mitarbeiter.weggeworfen":"Thrown away","mitarbeiter.erinnerung":"Reminder on your phone at {zeit}","mitarbeiter.erinnerung_an":"Turn on","mitarbeiter.keine_bereiche":"No areas yet","mitarbeiter.keine_bereiche_unter":"The boss sets them up in the setup.",
 "monat.1":"January","monat.2":"February","monat.3":"March","monat.4":"April","monat.5":"May","monat.6":"June","monat.7":"July","monat.8":"August","monat.9":"September","monat.10":"October","monat.11":"November","monat.12":"December",
 "nav.titel":"Main navigation","nav.assistent":"Assistant","nav.bestand":"Stock","nav.einkauf":"Shopping","nav.einkaufsliste":"Shopping list","nav.scannen":"Scan storage",
 "offline.kein_netz":"No signal. You can still scan.","offline.wird_hochgeladen":"Will upload as soon as there is signal","offline.titel":"Saved on the phone",
 "offline.wird_hochgeladen_lang":"No signal here. The photos are safe on the phone and will upload as soon as there is signal and the app is open.",
 "offline.fehler":"Upload failed – tap to retry",
 "rueckfrage.kurze_frage":"Quick question","rueckfrage.wie_viele":"How many {einheit} of {produkt} is that?","rueckfrage.weiss_nicht":"I don't know",
 "scan.hinweis":"Get the whole shelf in the picture. Several photos are fine.","scan.geist_hinweis":"Line the camera up with the faint picture.","scan.geist_aus":"Guide off","scan.geist_an":"Guide on",
 "scan.lampe":"Torch",
 "scan.zu_dunkel":"The photo is very dark. Add more light and take it again.",
 "scan.zu_dunkel_lampe":"The photo is very dark. Turn on the torch at the top and take it again.",
 "scan.kamera_app":"Tap the round button – the phone camera will open.",
 "bestaetigen.qualitaet_dunkel":"One photo was too dark – the numbers may be off.",
 "bestaetigen.qualitaet_unscharf":"One photo was blurry – the numbers may be off.",
 "bestaetigen.qualitaet_zu_weit":"One photo was taken from too far away – the numbers may be off.",
 "bestaetigen.qualitaet_verdeckt":"Some goods were hidden in one photo – the numbers may be off.",
 "bestaetigen.qualitaet_spiegelung":"One photo had reflections – the numbers may be off.",
 "bestaetigen.unbekannt":"Not in the catalog: {liste}. Should it be counted? Add it below under “{knopf}”.",
 "scan.foto":"Take photo","scan.fotos":P("{n} photo","{n} photos"),"scan.letztes_weg":"Delete last photo","scan.fertig":"Done","scan.naechste":"Next spot",
 "scan.schaue_an":"Let me have a look …","scan.erkennen_fehler":"Recognition didn't work.","scan.liegt_auf_geraet":"Don't worry: the photos are on the phone.",
 "scan.kamera_verweigert":"The camera isn't allowed. Please allow it in the phone settings.","scan.kamera_fehler":"The camera won't start.",
 "splash.slogan":"Your storage. Always in view.",
 "sprache.willkommen":"Welcome","sprache.frage":"Which language would you like to use?","sprache.sprechen":"Speak","sprache.fertig":"Done speaking",
 "sprache.wandelt":"Listening …","sprache.nichts_verstanden":"Didn't catch that. Please try again or type.",
 "team.titel":"Team","team.chef":"Boss","team.mitarbeiter":"Staff","team.einladen":"Invite staff","team.code_ist":"The code is","team.code_gueltig":"Valid for 14 days, for one person.",
 "team.per_whatsapp":"Send via WhatsApp","team.link_kopieren":"Copy link","team.kopiert":"Copied.","team.entfernen":"Remove","team.wirklich_entfernen":"Really remove {name}?",
 "team.einladung_text":"Hi! You've been invited to {betrieb} on The Chef. Open the link: {link} – or enter the code {code}.",
 "verlust.wert":"Value thrown away","verlust.vergleich":"{betrag} vs. {monat}","verlust.am_meisten":"Thrown away the most","verlust.tipp":"Tip from the assistant",
 "verlust.tipp_holen":"Get a tip","verlust.tipp_frage":"What was thrown away most this month and what can I do better?","verlust.ohne_preis":P("{n} report without price not counted","{n} reports without price not counted"),
 "vorlage.kuehlhaus":"Cold room","vorlage.tiefkuehler":"Freezer","vorlage.trocken":"Dry storage",
 "vorschlag.bestellen":"What do I need to order?","vorschlag.haehnchen":"Is there enough chicken for the weekend?","vorschlag.weggeworfen":"How much was thrown away?","vorschlag.tagesgericht":"What for dish of the day?",
 "weg.offline":"Saved on the phone – will upload once there is signal.","weg.warten":P("{n} waste report will upload once there is signal.","{n} waste reports will upload once there is signal."),"weg.fehler":"This waste report didn't go through: {produkt}, {menge}.","weg.verwerfen":"Discard","weg.frage":"What was thrown away?","weg.wie_viel":"How much?","weg.gespeichert":"Saved.",
 "zahl.tippen":"Type a number","zahl.sagen":"Say a number","zahl.oder_sagen":"or say it","zahl.verstanden":"“{text}” → {zahl}","zahl.nicht_verstanden":"“{text}” – no number recognised. Please type.",
 "zeit.nie":"never","zeit.heute":"today","zeit.gestern":"yesterday","zeit.heute_um":"today, {zeit}","zeit.gestern_um":"yesterday, {zeit}","zeit.vor_tagen":P("{n} day ago","{n} days ago"),
}
json.dump(dict(sorted(t.items())), open('public/sprachen/en.json','w'), ensure_ascii=False, indent=1)
print(len(t))
