import json
# Kurmancî (latînî). Piştî hejmarê navdêr yekjimar dimîne ("çar sindoq").
# ENTWURF – vor dem Start von Muttersprachlern prüfen lassen (THECHEF.md).
S=lambda x: {"one":x,"other":x}
t = {
 "allg.fertig":"Temam","allg.gespeichert":"Hate tomarkirin","allg.hinzufuegen":"Lê zêde bike","allg.loeschen":"Jê bibe","allg.los":"Em dest pê bikin","allg.mehr":"Bêtir","allg.nochmal":"Dîsa biceribîne",
 "allg.schliessen":"Bigire","allg.senden":"Bişîne","allg.spaeter":"Paşê","allg.speichern":"Tomar bike","allg.weiter":"Berdewam","allg.weniger":"Kêmtir","allg.zurueck":"Paş",
 "ampel.gut":"Her tişt baş e","ampel.knapp":"Kêm dibe","ampel.knapp_kurz":"kêm","ampel.sofort":"Yekser",
 "anmelden.titel":"Bi xêr hatî","anmelden.unter":"Tu kî yî?","anmelden.ich_chef":"Ez serok im","anmelden.ich_chef_unter":"Karsaziyê çêke an têkeve",
 "anmelden.ich_mitarbeiter":"Ez li vir dixebitim","anmelden.ich_mitarbeiter_unter":"Bi koda serok","anmelden.anmelden":"Têkeve","anmelden.neu":"Nû me",
 "anmelden.konto_anlegen":"Hesab çêke","anmelden.email":"E-name","anmelden.passwort":"Şîfre (herî kêm 8 tîp)","anmelden.code":"Koda serok",
 "anmelden.dein_name":"Navê te","anmelden.mail_bestaetigen":"Hema hema: me e-nameyek şand {email}. Ji kerema xwe li girêdanê bitikîne.",
 "anmelden.demo_hinweis":"Demo: bê server, tenê ji bo dîtinê. Naskirin tê simulekirin.",
 "antwort.noch_da":"Heye","antwort.brauchst":"Pêwîst e","antwort.fehlt":"Kêm e",
 "assistent.morgen":"Beyanî baş","assistent.tag":"Roj baş","assistent.abend":"Êvar baş",
 "assistent.gescannt":"Îro hate skankirin · {zeit} · {wer}","assistent.teilweise":"Îro {n} ji {von} hate skankirin",
 "assistent.nicht_gescannt":"Îro nehate skankirin","assistent.es_fehlt":"Kêm e: {bereiche}","assistent.zahlen_alt":"Hejmar ji skana dawî ne: {wann}.",
 "assistent.selbst_scannen":"Niha skan bike","assistent.briefing":"Kurteya êvarê","assistent.stand_jetzt":"Rewş niha","assistent.vorlesen":"Bi deng bixwîne",
 "assistent.zum_bestand":"Ber bi stokê","assistent.hinweise":"Hişyarî","assistent.tagesgericht":"Ramana xwarina rojê",
 "assistent.tagesgericht_fehler":"Niha ti raman nayê.","assistent.frag_mich":"Tiştekî ji min bipirse …",
 "assistent.verworfen":"Niha ez nikarim vê bi ewlehî bibêjim. Ji kerema xwe dîsa skan bike an cuda bipirse.",
 "bestaetigen.titel":"Min ev nas kirin","bestaetigen.unter":"Hemû rast e? Ji bo guhertinê li qutîkê bitikîne.",
 "bestaetigen.test_titel":"Ji kerema xwe bi xwe bijmêre","bestaetigen.test_unter":"Ceribandina rastbûnê: li her qutîkê bitikîne û hejmara rast binivîse.",
 "bestaetigen.nichts_erkannt":"Min tiştek ji katalogê nas nekir. Bi dest lê zêde bike an wêneyek nû bikişîne.",
 "bestaetigen.unsicher":"ne ewle","bestaetigen.von_hand":"hate zêdekirin","bestaetigen.zaehlen":"bijmêre","bestaetigen.fehlt_etwas":"Tiştek kêm e?",
 "bestaetigen.speichern":"Hemû rast e – tomar bike","bestaetigen.noch_offen":S("Hîn {n} bijmêre"),"bestaetigen.noch_foto":"Wêneyek din bikişîne",
 "bestaetigen.mhd":"Heta kengê baş e (eger li ser etîketê be)","bestaetigen.nicht_da":"Tune ({zahl})","bestaetigen.schon_gespeichert":"Ev skan berê hatiye tomarkirin.",
 "bestand.titel":"Stok","bestand.letzter_scan":"Skana dawî: {wann}","bestand.ware_im_lager":"Mal di depoyê de","bestand.weggeworfen_monat":"Avêtî {monat}",
 "bestand.ohne_preis":S("{n} berhem bê biha"),"bestand.ampel":"Ronahiya trafîkê","bestand.laeuft_bald_ab":"Zû xera dibe",
 "bestand.mhd_berechnet":"texmînî (bê etîket)","bestand.alles":"Hemû di depoyê de","bestand.scan":"Skan: {wann}","bestand.mindestens":"Herî kêm: {menge}",
 "bestand.leer":"Hîn berhem di katalogê de tune.","bestand.produkte_anlegen":"Berheman zêde bike",
 "briefing.laeuft_ab":"{produkt} {wann} xera dibe.","briefing.abgelaufen":"{produkt} xera bûye.","briefing.nichts_laeuft_ab":"Di 2 rojên pêş de tiştek xera nabe.",
 "briefing.knapp":"{produkt} kêm dibe.","briefing.bestellen":"{menge} ferman bike","briefing.alles_da":"Hemû li ser herî kêm in.",
 "briefing.einkauf":"Kirîna sibê:","briefing.artikel":S("{n} tişt"),
 "demo.bestand_satz":"{produkt}: {menge} heye.","demo.einkauf_satz":S("Divê tu {n} tiştî ferman bikî."),
 "demo.reicht_ja":"Erê, têr dike.","demo.reicht_nein":"Na, nêzîkî {menge} kêm e.","demo.zu_wenig_daten":"Ji bo vê hîn skan têr nînin. Piştî çend rojan ez dikarim texmîn bikim.",
 "demo.quelle_bestand":"Ji skana te ya dawî.","demo.quelle_verbrauch":"Ji skanên te yên {tage} rojên dawî hate texmînkirin.","demo.quelle_weg":"Ji qeydên avêtinê.",
 "demo.weg_satz":"Vê mehê {betrag}.","demo.unbekannt":"Di demoyê de ez tenê van fam dikim: ferman, „Çiqas … heye?“, „… têr dike?“ û avêtî.",
 "demo.tagesgericht":"Tebaqa bi {produkt}.","demo.tagesgericht_grund":"{produkt} ku zû xera dibe bi kar tîne.",
 "einheit.kiste":S("sindoq"),"einheit.packung":S("pake"),"einheit.stueck":S("hebe"),"einheit.becher":S("tas"),
 "einheit.beutel":S("tûrik"),"einheit.flasche":S("şûşe"),"einheit.dose":S("qutî"),"einheit.eimer":S("satil"),
 "einheit.sack":S("çewal"),"einheit.karton":S("karton"),"einheit.glas":S("şûşeya devgirtî"),"einheit.netz":S("tor"),
 "einheit.spiess":S("şîş"),"einheit.kg":S("kg"),"einheit.l":S("l"),
 "einkauf.titel":"Kirîna ji bo sibê","einkauf.erstellt":"Alîkar amade kir · Rewş: {wann}","einkauf.muessen":S("tişt divê dîsa bê fermankirin"),
 "einkauf.nichts":"Tiştek ji bo fermanê tune. Hemû li ser herî kêm in.","einkauf.noch_da":"Heye: {menge}","einkauf.laeuft_ab":"Îro xera dibe",
 "einkauf.email":"E-name","einkauf.teilen_titel":"Kirîna {datum}:","einkauf.anzahl":S("{n} tişt"),
 "einrichtung.schritt":"Gav {n} ji {von}","einrichtung.betrieb_titel":"Karsaziya te","einrichtung.betrieb_name":"Navê karsaziyê",
 "einrichtung.bereiche_titel":"Cih û cihên wêneyan","einrichtung.produkte_titel":"Berhem","einrichtung.team_titel":"Karmendan vexwîne",
 "einrichtung.iphone_titel":"Deyne ser telefonê","einrichtung.fertig":"Qediya – em dest pê bikin",
 "einstellungen.titel":"Mîheng","einstellungen.modus":"Awa","einstellungen.hell":"Ronî","einstellungen.dunkel":"Tarî","einstellungen.auto":"Otomatîk",
 "einstellungen.akzent":"Rengê giring","einstellungen.akzent_warum":"Kesk, zer û sor wek rengê giring tune – ew rengên ronahiya trafîkê ne.",
 "einstellungen.glas":"Cam","einstellungen.klar":"Zelal","einstellungen.getoent":"Rengkirî","einstellungen.bewegung":"Tevger","einstellungen.bewegung_unter":"Anîmasyonên kurt dema vekirinê",
 "einstellungen.sprache":"Ziman","einstellungen.push":"Agahdarî","einstellungen.push_unter":"Tiştên girîng û kurteya êvarê li ser telefonê",
 "einstellungen.betrieb":"Karsazî","einstellungen.erinnerung":"Bîranîna skanê ji bo karmendan","einstellungen.loeschfrist":"Wêneyên skanê jê bibe piştî",
 "einstellungen.tage":S("{n} rojan"),"einstellungen.loeschfrist_warum":"Dibe ku karmend di wêneyan de xuya bibin. Hejmarên naskirî dimînin.",
 "einstellungen.test":"Ceribandina rastbûnê","einstellungen.test_unter":"Karmend bi xwe dijmêrin, bêyî ku hejmara zekaya çêkirî bibînin",
 "einstellungen.abmelden":"Derkeve","einstellungen.demo_reset":"Demoyê ji nû ve saz bike",
 "akzent.blau":"Şîn","akzent.lila":"Mor","akzent.petrol":"Şînê kesk",
 "fehler.unbekannt":"Tiştek xelet çû.","fehler.verbindung":"Girêdana bi serverê re tune.","fehler.laden":"Nehate barkirin.",
 "fehler.speichern":"Nehate tomarkirin.","fehler.nicht_angemeldet":"Ji kerema xwe dîsa têkeve.","fehler.server":"Serverê xeletiyek ragihand.",
 "fehler.foto":"Wêne nehate barkirin.","fehler.anmelden":"Têketin nebû. E-name û şîfreyê kontrol bike.",
 "fehler.registrieren":"Hesab nehate çêkirin.","fehler.beitreten":"Tevlîbûn nebû.","fehler.code_ungueltig":"Kod şaş e an berê hatiye bikaranîn.",
 "fehler.sprache":"Deng nehate veguhertin. Ji kerema xwe binivîse.","fehler.sprache_demo":"Ketina bi deng serverê dixwaze – di demoyê de ji kerema xwe binivîse.",
 "fehler.demo":"Di demoyê de ne gengaz e.","fehler.keine_kamera":"Di vê cîhazê de kamera ji bo gerokê tune.","fehler.kein_mikrofon":"Mîkrofon tune. Ji kerema xwe binivîse.",
 "fehler.push_ios_installieren":"Li ser iPhone agahdarî tenê dixebitin eger sepan li ser ekrana malê be.","fehler.push_nicht_moeglich":"Ev cîhaz nikare agahdariyê bistîne.",
 "fehler.push_abgelehnt":"Agahdarî hatin redkirin. Di mîhengên telefonê de destûr bide.","fehler.push_nicht_eingerichtet":"Agahdarî hîn li serverê nehatine sazkirin.",
 "genauigkeit.titel":"Rastbûna naskirinê","genauigkeit.erklaerung":"Ya ku zekaya çêkirî nas kir li hember ya ku di pejirandinê de hate jimartin. 30 rojên dawî.",
 "genauigkeit.keine_daten":"Hîn skanên pejirandî tune.","genauigkeit.genau":"Tam rast","genauigkeit.gezaehlt":"Hate jimartin","genauigkeit.uebersehen":"Ji çav reviya",
 "genauigkeit.zeile":"{genau} ji {n} tam · navîn {abw} cuda",
 "gespeichert.titel":"Hate tomarkirin.","gespeichert.danke":"Spas, {name}. Serok niha her tiştî dibîne.","gespeichert.zusammenfassung":S("{n} berhem · {bereich} · {zeit}"),
 "gespeichert.als_naechstes":"Ya din: {bereich}","gespeichert.weiter_scannen":"Skanê bidomîne","gespeichert.fertig_heute":"Ji bo îro qediya","gespeichert.alles_fertig":"Îro hemû cih qediyan.",
 "gespraech.leer":"Li ser depoyê tiştekî bipirse – bi nivîsê an mîkrofonê.","gespraech.auf_liste":"Li ser lîsteya kirînê ye.","gespraech.daten_alt":"Dane kevn in – ji kerema xwe dîsa skan bike.",
 "gespraech.schaetzung":"Texmîn","gespraech.stand":"Rewş: skan {wann}.","gespraech.verworfen_warum":"Hejmarek di bersiva min de di daneyên te de tunebû – ji ber vê min ew nîşan neda.",
 "hinweis.abgelaufen":"{produkt} xera bûye.","hinweis.laeuft_ab":"{produkt} {wann} xera dibe.","hinweis.leer":"{produkt} qediya.","hinweis.knapp":"{produkt} kêm dibe.",
 "hinweis.bestellen":"{menge} ferman bike","hinweis.fehlen":"{menge} kêm e.","hinweis.nicht_gescannt":"Îro nehate skankirin.","hinweis.zur_liste":"Ser lîsteya kirînê","hinweis.erledigt":"Temam",
 "installieren.titel":"Sepanê deyne ser telefonê","installieren.schon":"Sepan berê li ser ekrana malê ye.",
 "installieren.warum_ios":"Li ser iPhone agahdarî tenê tên eger sepan li ser ekrana malê be. Di Safari de wiha:",
 "installieren.warum":"Tu sepanê wiha dideynî ser ekrana malê:","installieren.ios_1":"Li jêr li „Parve bike“ bitikîne (qutî bi tîrê ber bi jor).",
 "installieren.ios_2":"„Li Ekrana Malê Zêde Bike“ hilbijêre.","installieren.ios_3":"Li jor li „Zêde bike“ bitikîne.","installieren.ios_4":"Ji niha û pê ve The Chef ji îkonê veke.",
 "installieren.andere_1":"Li jor menûyê (⋮) veke.","installieren.andere_2":"„Sepanê saz bike“ an „Li ekrana malê zêde bike“ hilbijêre.",
 "katalog.bereiche":"Cih û cihên wêneyan","katalog.produkte":"Berhem","katalog.bereiche_erklaerung":"Cih ew der in ku her roj têne skankirin. Ji bo her cihî cihên wêneyan ên sabît diyar dikî – her car bi heman awayî kişandin jimartina rasttir e.",
 "katalog.positionen":"Cihên wêneyan","katalog.position":"Cihê wêneyê","katalog.position_neu":"Cihê wêneyê zêde bike","katalog.mit_foto":"bi wêneyê referansê","katalog.ohne_foto":"hîn bê wêneyê referansê",
 "katalog.bereich_neu":"Cih zêde bike","katalog.eigener_bereich":"Navê xwe …","katalog.referenzfoto":"Wêneyê referansê bikişîne",
 "katalog.referenzfoto_erklaerung":"Carekê wek ku her roj dê bikişînî bikişîne. Wêne di skanê de nîv-zelal wek alîkarî xuya dibe.",
 "katalog.wirklich_loeschen":"Bi rastî jê bibî? Dîrok dimîne.","katalog.name":"Nav","katalog.uebersetzen":"Zimanên din pêşniyar bike","katalog.vorschlag":"Pêşniyar – ji kerema xwe kontrol bike",
 "katalog.produkte_erklaerung":"Her berhemê carekê bikişîne û diyar bike ka çawa tê jimartin. Zekaya çêkirî tenê yekeyan dijmêre û bi xwe diguherîne.",
 "katalog.produkt_neu":"Berhem zêde bike","katalog.noch_keine":"Hîn berhem tune.","katalog.foto":"Wêneyê berhemê","katalog.foto_warum":"Alîkariya zekaya çêkirî dike ku nas bike.",
 "katalog.kategorie":"Cure","katalog.wie_zaehlen":"Çawa tê jimartin?","katalog.wie_zaehlen_unter":"Li ser refikê çi xuya dibe? Sindoq, tas, hebe …",
 "katalog.zaehleinheit":"Yeka li ser refikê","katalog.inhalt":"Naverok ji bo her yekeyê (bijarte)","katalog.basiseinheit":"bi","katalog.beispiel":"1 {einheit} = {menge} {basis}",
 "katalog.mindestbestand":"Herî kêm ({einheit})","katalog.haltbarkeit":"Diman (roj)","katalog.preis":"Biha ji bo her {einheit} bi € (bijarte)","katalog.wo":"Li ku ye?",
 "kategorie.fleisch":"Goşt","kategorie.fisch":"Masî","kategorie.gemuese":"Sebze","kategorie.obst":"Fêkî","kategorie.milch":"Berhemên şîr","kategorie.brot":"Nan û hevîr",
 "kategorie.tiefkuehl":"Cemidî","kategorie.trocken":"Tiştên hişk","kategorie.getraenke":"Vexwarin","kategorie.sonstiges":"Yên din",
 "kosten.titel":"Lêçûnên zekaya çêkirî","kosten.letzte_30":"30 rojên dawî","kosten.zeile":S("{n} bang · navîn {je} · navîn {tokens} token"),
 "kosten.keine":"Hîn lêçûn tune.","kosten.je_betrieb":"Ji bo her karsaziyê","kosten.hinweis":"Ji dolarê bi rêjeyek sabît hate guhertin. Fatûreya Anthropic esas e.",
 "kosten.scan":"Naskirina skanê","kosten.assistent":"Alîkar","kosten.briefing":"Kurte","kosten.sprache":"Ketina bi deng","kosten.uebersetzung":"Werger","kosten.tagesgericht":"Xwarina rojê",
 "aktion.einkaufsliste":"Ser lîsteya kirînê zêde bike","aktion.bestand":"Stokê bibîne","aktion.verlust":"Kurteyê bibîne","aktion.einkauf":"Lîsteya kirînê veke","aktion.neu_scannen":"Niha skan bike",
 "mhd.abgelaufen":"xera bûye","mhd.heute":"îro","mhd.morgen":"sibê","mhd.tage":S("{n} roj"),"mhd.in_tagen":S("di {n} rojan de"),
 "mitarbeiter.hallo":"Silav, {name}","mitarbeiter.sprache_waehlen":"Ziman hilbijêre","mitarbeiter.heute":"Îro skan bike","mitarbeiter.fortschritt":"{n} ji {von} qediya",
 "mitarbeiter.jetzt_dran":"Niha dora te ye","mitarbeiter.erledigt":"Qediya · {zeit}","mitarbeiter.offen":"Vekirî","mitarbeiter.bitte_bestaetigen":"Ji kerema xwe bipejirîne",
 "mitarbeiter.weggeworfen":"Hate avêtin","mitarbeiter.keine_bereiche":"Hîn cih tune","mitarbeiter.keine_bereiche_unter":"Serok wan di sazkirinê de zêde dike.",
 "monat.1":"Çile","monat.2":"Sibat","monat.3":"Adar","monat.4":"Nîsan","monat.5":"Gulan","monat.6":"Hezîran","monat.7":"Tîrmeh","monat.8":"Tebax","monat.9":"Îlon","monat.10":"Cotmeh","monat.11":"Mijdar","monat.12":"Kanûn",
 "nav.titel":"Navîgasyona sereke","nav.assistent":"Alîkar","nav.bestand":"Stok","nav.einkauf":"Kirîn","nav.einkaufsliste":"Lîsteya kirînê","nav.scannen":"Depoyê skan bike",
 "offline.kein_netz":"Tor tune. Tu dîsa jî dikarî skan bikî.","offline.wird_hochgeladen":"Dema tor hebe dê bê barkirin","offline.titel":"Li ser telefonê hate tomarkirin",
 "offline.wird_hochgeladen_lang":"Li vir tor tune. Wêne li ser telefonê ewle ne û dema tor hebe û sepan vekirî be dê bên barkirin.",
 "offline.fehler":"Barkirin nebû – ji bo dubarekirinê bitikîne",
 "rueckfrage.kurze_frage":"Pirsa kurt","rueckfrage.wie_viele":"Ev çend {einheit} {produkt} in?","rueckfrage.weiss_nicht":"Nizanim",
 "scan.hinweis":"Tevahiya refikê têxe wêneyê. Çend wêne baş in.","scan.geist_hinweis":"Kamerayê li gorî wêneyê zelal rast bike.","scan.geist_aus":"Wêneyê alîkar veşêre","scan.geist_an":"Wêneyê alîkar nîşan bide",
 "scan.lampe":"Çira","scan.foto":"Wêne bikişîne","scan.fotos":S("{n} wêne"),"scan.letztes_weg":"Wêneyê dawî jê bibe","scan.fertig":"Qediya","scan.naechste":"Cihê din",
 "scan.schaue_an":"Ez lê dinêrim …","scan.erkennen_fehler":"Naskirin nebû.","scan.liegt_auf_geraet":"Xem neke: wêne li ser telefonê ne.",
 "scan.kamera_verweigert":"Destûra kamerayê tune. Ji kerema xwe di mîhengên telefonê de destûr bide.","scan.kamera_fehler":"Kamera dest pê nake.",
 "splash.slogan":"Depoya te. Her dem li ber çavan.",
 "sprache.willkommen":"Bi xêr hatî","sprache.frage":"Tu dixwazî sepanê bi kîjan zimanî bi kar bînî?","sprache.sprechen":"Biaxive","sprache.fertig":"Axaftin qediya",
 "sprache.wandelt":"Ez guhdarî dikim …","sprache.nichts_verstanden":"Min fam nekir. Ji kerema xwe dîsa bibêje an binivîse.",
 "team.titel":"Tîm","team.chef":"Serok","team.mitarbeiter":"Karmend","team.einladen":"Karmend vexwîne","team.code_ist":"Kod ev e","team.code_gueltig":"14 rojan derbasdar e, ji bo kesekî.",
 "team.per_whatsapp":"Bi WhatsApp bişîne","team.link_kopieren":"Girêdanê kopî bike","team.kopiert":"Hate kopîkirin.","team.entfernen":"Rake","team.wirklich_entfernen":"Bi rastî {name} rakî?",
 "team.einladung_text":"Silav! Tu li The Chef ji bo {betrieb} hatî vexwendin. Girêdanê veke: {link} – an koda {code} binivîse.",
 "verlust.wert":"Nirxê avêtî","verlust.vergleich":"{betrag} li hember {monat}","verlust.am_meisten":"Herî zêde hate avêtin","verlust.tipp":"Şîreta alîkar",
 "verlust.tipp_holen":"Şîretê bistîne","verlust.tipp_frage":"Vê mehê herî zêde çi hate avêtin û ez dikarim çi baştir bikim?","verlust.ohne_preis":S("{n} qeyd bê biha nehatin hesibandin"),
 "vorlage.kuehlhaus":"Odeya sar","vorlage.tiefkuehler":"Cemidok","vorlage.trocken":"Depoya hişk",
 "vorschlag.bestellen":"Divê ez çi ferman bikim?","vorschlag.haehnchen":"Mirîşk ji bo dawiya hefteyê têr dike?","vorschlag.weggeworfen":"Çiqas hate avêtin?","vorschlag.tagesgericht":"Xwarina rojê çi be?",
 "weg.frage":"Çi hate avêtin?","weg.wie_viel":"Çiqas?","weg.gespeichert":"Hate tomarkirin.",
 "zahl.tippen":"Hejmarê binivîse","zahl.sagen":"Hejmarê bibêje","zahl.oder_sagen":"an bibêje","zahl.verstanden":"„{text}“ → {zahl}","zahl.nicht_verstanden":"„{text}“ – hejmar nehate naskirin. Ji kerema xwe binivîse.",
 "zeit.nie":"qet","zeit.heute":"îro","zeit.gestern":"duh","zeit.heute_um":"îro, {zeit}","zeit.gestern_um":"duh, {zeit}","zeit.vor_tagen":S("{n} roj berê"),
}
json.dump(dict(sorted(t.items())), open('public/sprachen/ku.json','w'), ensure_ascii=False, indent=1)
print(len(t))
