import json
S=lambda x: {"one":x,"other":x}  # Türkçe: sayıdan sonra tekil
t = {
 "allg.fertig":"Tamam","allg.gespeichert":"Kaydedildi","allg.hinzufuegen":"Ekle","allg.loeschen":"Sil","allg.los":"Başlayalım","allg.mehr":"Daha fazla","allg.nochmal":"Tekrar dene",
 "allg.schliessen":"Kapat","allg.senden":"Gönder","allg.spaeter":"Sonra","allg.speichern":"Kaydet","allg.weiter":"Devam","allg.weniger":"Daha az","allg.zurueck":"Geri",
 "ampel.gut":"Her şey yolunda","ampel.knapp":"Azalıyor","ampel.knapp_kurz":"az","ampel.sofort":"Acil",
 "anmelden.titel":"Hoş geldin","anmelden.unter":"Sen kimsin?","anmelden.ich_chef":"Patron benim","anmelden.ich_chef_unter":"İşletme oluştur veya giriş yap",
 "anmelden.ich_mitarbeiter":"Burada çalışıyorum","anmelden.ich_mitarbeiter_unter":"Patronun verdiği kodla","anmelden.anmelden":"Giriş yap","anmelden.neu":"Yeniyim",
 "anmelden.konto_anlegen":"Hesap oluştur","anmelden.email":"E-posta","anmelden.passwort":"Şifre (en az 8 karakter)","anmelden.code":"Patronun kodu",
 "anmelden.dein_name":"Adın","anmelden.mail_bestaetigen":"Az kaldı: {email} adresine bir e-posta gönderdik. Lütfen içindeki bağlantıya dokun.",
 "anmelden.demo_hinweis":"Demo: sunucu yok, sadece bakmak için. Tanıma simüle ediliyor.",
 "antwort.noch_da":"Elde var","antwort.brauchst":"Gereken","antwort.fehlt":"Eksik",
 "assistent.morgen":"Günaydın","assistent.tag":"İyi günler","assistent.abend":"İyi akşamlar",
 "assistent.gescannt":"Bugün tarandı · {zeit} · {wer}","assistent.teilweise":"Bugün {von} alandan {n} tarandı",
 "assistent.nicht_gescannt":"Bugün taranmadı","assistent.es_fehlt":"Eksik: {bereiche}","assistent.zahlen_alt":"Rakamlar son taramadan: {wann}.",
 "assistent.selbst_scannen":"Şimdi tara","assistent.briefing":"Akşam özeti","assistent.stand_jetzt":"Şu anki durum","assistent.vorlesen":"Sesli oku",
 "assistent.zum_bestand":"Stoka git","assistent.wichtig":S("{n} önemli konu"),"assistent.hinweise":"Uyarılar","assistent.tagesgericht":"Günün yemeği fikri",
 "assistent.tagesgericht_fehler":"Şu an fikir alınamıyor.","assistent.frag_mich":"Bana bir şey sor …",
 "assistent.verworfen":"Bunu şu an kesin söyleyemem. Lütfen yeniden tara veya farklı sor.",
 "bestaetigen.titel":"Bunları tanıdım","bestaetigen.unter":"Hepsi doğru mu? Değiştirmek için bir kutuya dokun.",
 "bestaetigen.test_titel":"Lütfen kendin say","bestaetigen.test_unter":"Doğruluk testi: Her kutuya dokun ve gerçekte kaç tane olduğunu gir.",
 "bestaetigen.nichts_erkannt":"Katalogdan hiçbir şey tanımadım. Elle ekle veya yeni fotoğraf çek.",
 "bestaetigen.unsicher":"emin değil","bestaetigen.von_hand":"eklendi","bestaetigen.zaehlen":"say","bestaetigen.fehlt_etwas":"Eksik bir şey var mı?",
 "bestaetigen.speichern":"Hepsi doğru – kaydet","bestaetigen.noch_offen":S("{n} tane daha say"),"bestaetigen.noch_foto":"Bir fotoğraf daha çek",
 "bestaetigen.mhd":"Son kullanma tarihi (etikette varsa)","bestaetigen.nicht_da":"Yok ({zahl})","bestaetigen.schon_gespeichert":"Bu tarama zaten kaydedildi.",
 "bestand.titel":"Stok","bestand.letzter_scan":"Son tarama: {wann}","bestand.ware_im_lager":"Depodaki mal","bestand.weggeworfen_monat":"Çöpe atılan {monat}",
 "bestand.ohne_preis":S("{n} ürünün fiyatı yok"),"bestand.ampel":"Trafik ışığı","bestand.laeuft_bald_ab":"Yakında bozulacak",
 "bestand.mhd_berechnet":"tahmini (etiket yok)","bestand.alles":"Depodaki her şey","bestand.scan":"Tarama: {wann}","bestand.mindestens":"En az: {menge}",
 "bestand.leer":"Katalogda henüz ürün yok.","bestand.produkte_anlegen":"Ürün ekle",
 "briefing.laeuft_ab":"{produkt} {wann} bozuluyor.","briefing.abgelaufen":"{produkt} bozulmuş.","briefing.nichts_laeuft_ab":"Önümüzdeki 2 günde bozulan bir şey yok.",
 "briefing.knapp":"{produkt} azalıyor.","briefing.bestellen":"{menge} sipariş et","briefing.alles_da":"Her şey en az stokun üstünde.",
 "briefing.einkauf":"Yarın alınacak:","briefing.artikel":S("{n} ürün"),
 "demo.bestand_satz":"{produkt}: {menge} var.","demo.einkauf_satz":S("{n} ürün sipariş etmen gerekiyor."),
 "demo.reicht_ja":"Evet, yeter.","demo.reicht_nein":"Hayır, yaklaşık {menge} eksik.","demo.zu_wenig_daten":"Bunun için henüz yeterli tarama yok. Birkaç gün sonra tahmin edebilirim.",
 "demo.quelle_bestand":"Son taramandan.","demo.quelle_verbrauch":"Son {tage} günün taramalarından tahmin edildi.","demo.quelle_weg":"Çöpe atılan kayıtlarından.",
 "demo.weg_satz":"Bu ay {betrag}.","demo.unbekannt":"Demo modunda sadece şunları anlıyorum: sipariş, „Ne kadar … var?“, „… yeter mi?“ ve çöpe atılan.",
 "demo.tagesgericht":"{produkt} tabağı.","demo.tagesgericht_grund":"Yakında bozulacak {produkt} kullanılır.",
 "einheit.kiste":S("kasa"),"einheit.packung":S("paket"),"einheit.stueck":S("adet"),"einheit.becher":S("kova"),
 "einheit.beutel":S("poşet"),"einheit.flasche":S("şişe"),"einheit.dose":S("kutu"),"einheit.eimer":S("kova"),
 "einheit.sack":S("çuval"),"einheit.karton":S("koli"),"einheit.glas":S("kavanoz"),"einheit.netz":S("file"),
 "einheit.spiess":S("şiş"),"einheit.kg":S("kg"),"einheit.l":S("l"),
 "einkauf.titel":"Yarın için alışveriş","einkauf.erstellt":"Asistan hazırladı · Durum: {wann}","einkauf.muessen":S("ürün yeniden sipariş edilmeli"),
 "einkauf.nichts":"Sipariş gerekmiyor. Her şey en az stokun üstünde.","einkauf.noch_da":"Elde: {menge}","einkauf.laeuft_ab":"Bugün bozuluyor",
 "einkauf.email":"E-posta","einkauf.teilen_titel":"{datum} alışverişi:","einkauf.anzahl":S("{n} ürün"),
 "einrichtung.schritt":"Adım {n} / {von}","einrichtung.betrieb_titel":"İşletmen","einrichtung.betrieb_name":"İşletmenin adı",
 "einrichtung.bereiche_titel":"Alanlar ve fotoğraf yerleri","einrichtung.produkte_titel":"Ürünler","einrichtung.team_titel":"Çalışan davet et",
 "einrichtung.iphone_titel":"Telefona ekle","einrichtung.fertig":"Bitti – başlayalım",
 "einstellungen.titel":"Ayarlar","einstellungen.modus":"Mod","einstellungen.hell":"Açık","einstellungen.dunkel":"Koyu","einstellungen.auto":"Otomatik",
 "einstellungen.akzent":"Vurgu rengi","einstellungen.akzent_warum":"Yeşil, sarı ve kırmızı vurgu olarak yok – bunlar trafik ışığı renkleri.",
 "einstellungen.glas":"Cam","einstellungen.klar":"Şeffaf","einstellungen.getoent":"Renkli","einstellungen.bewegung":"Hareketler","einstellungen.bewegung_unter":"Açılışta kısa animasyonlar",
 "einstellungen.sprache":"Dil","einstellungen.push":"Bildirimler","einstellungen.push_unter":"Önemli şeyler ve akşam özeti telefona",
 "einstellungen.betrieb":"İşletme","einstellungen.erinnerung":"Çalışanlar için tarama hatırlatması","einstellungen.loeschfrist":"Tarama fotoğraflarını sil",
 "einstellungen.tage":S("{n} gün sonra"),"einstellungen.loeschfrist_warum":"Fotoğraflarda çalışanlar görünebilir. Tanınan rakamlar kalır.",
 "einstellungen.test":"Doğruluk testi","einstellungen.test_unter":"Çalışanlar yapay zekânın rakamını görmeden kendileri sayar",
 "einstellungen.abmelden":"Çıkış yap","einstellungen.demo_reset":"Demoyu sıfırla",
 "akzent.blau":"Mavi","akzent.lila":"Mor","akzent.petrol":"Petrol mavisi",
 "fehler.unbekannt":"Bir şeyler ters gitti.","fehler.verbindung":"Sunucuya bağlantı yok.","fehler.laden":"Yüklenemedi.",
 "fehler.speichern":"Kaydedilemedi.","fehler.nicht_angemeldet":"Lütfen yeniden giriş yap.","fehler.server":"Sunucu bir hata bildirdi.",
 "fehler.foto":"Fotoğraf yüklenemedi.","fehler.anmelden":"Giriş olmadı. E-posta ve şifreyi kontrol et.",
 "fehler.registrieren":"Hesap oluşturulamadı.","fehler.beitreten":"Katılma olmadı.","fehler.code_ungueltig":"Kod yanlış veya zaten kullanılmış.",
 "fehler.sprache":"Ses yazıya çevrilemedi. Lütfen yaz.","fehler.sprache_demo":"Sesli giriş sunucu ister – demoda lütfen yaz.",
 "fehler.demo":"Demoda mümkün değil.","fehler.keine_kamera":"Bu cihazda tarayıcı için kamera yok.","fehler.kein_mikrofon":"Mikrofon yok. Lütfen yaz.",
 "fehler.push_ios_installieren":"iPhone'da bildirimler sadece uygulama ana ekrandaysa çalışır.","fehler.push_nicht_moeglich":"Bu cihaz bildirim alamıyor.",
 "fehler.push_abgelehnt":"Bildirimler reddedildi. Telefon ayarlarından izin ver.","fehler.push_nicht_eingerichtet":"Bildirimler sunucuda henüz kurulmadı.",
 "genauigkeit.titel":"Tanıma doğruluğu","genauigkeit.erklaerung":"Yapay zekânın tanıdığı ile onaylarken sayılanın karşılaştırması. Son 30 gün.",
 "genauigkeit.keine_daten":"Henüz onaylanmış tarama yok.","genauigkeit.genau":"Tam doğru","genauigkeit.gezaehlt":"Sayılan","genauigkeit.uebersehen":"Gözden kaçan",
 "genauigkeit.zeile":"{n} içinden {genau} tam · ort. {abw} fark",
 "gespeichert.titel":"Kaydedildi.","gespeichert.danke":"Teşekkürler, {name}. Patron artık her şeyi görüyor.","gespeichert.zusammenfassung":S("{n} ürün · {bereich} · {zeit}"),
 "gespeichert.als_naechstes":"Sırada: {bereich}","gespeichert.weiter_scannen":"Taramaya devam","gespeichert.fertig_heute":"Bugünlük bitti","gespeichert.alles_fertig":"Bugün tüm alanlar tamam.",
 "gespraech.leer":"Depo hakkında bir şey sor – yazarak veya mikrofonla.","gespraech.auf_liste":"Alışveriş listesinde.","gespraech.daten_alt":"Veriler eski – lütfen yeniden tara.",
 "gespraech.schaetzung":"Tahmin","gespraech.stand":"Durum: tarama {wann}.","gespraech.verworfen_warum":"Cevabımdaki bir rakam verilerinde yoktu – bu yüzden göstermedim.",
 "hinweis.abgelaufen":"{produkt} bozulmuş.","hinweis.laeuft_ab":"{produkt} {wann} bozuluyor.","hinweis.leer":"{produkt} bitti.","hinweis.knapp":"{produkt} azalıyor.",
 "hinweis.bestellen":"{menge} sipariş et","hinweis.fehlen":"{menge} eksik.","hinweis.nicht_gescannt":"Bugün taranmadı.","hinweis.zur_liste":"Alışveriş listesine","hinweis.erledigt":"Tamam",
 "installieren.titel":"Uygulamayı telefona ekle","installieren.schon":"Uygulama zaten ana ekranda.",
 "installieren.warum_ios":"iPhone'da bildirimler sadece uygulama ana ekrandaysa gelir. Safari'de şöyle:",
 "installieren.warum":"Uygulamayı ana ekrana böyle eklersin:","installieren.ios_1":"Alttaki „Paylaş“a dokun (yukarı oklu kutu).",
 "installieren.ios_2":"„Ana Ekrana Ekle“yi seç.","installieren.ios_3":"Sağ üstte „Ekle“ye dokun.","installieren.ios_4":"Bundan sonra The Chef'i simgeden aç.",
 "installieren.andere_1":"Sağ üstteki menüyü (⋮) aç.","installieren.andere_2":"„Uygulamayı yükle“ veya „Ana ekrana ekle“yi seç.",
 "katalog.bereiche":"Alanlar ve fotoğraf yerleri","katalog.produkte":"Ürünler","katalog.bereiche_erklaerung":"Alanlar her gün taranan yerlerdir. Her alan için sabit fotoğraf yerleri belirlersin – hep aynı şekilde çekmek daha doğru sayım demektir.",
 "katalog.positionen":"Fotoğraf yerleri","katalog.position":"Fotoğraf yeri","katalog.position_neu":"Fotoğraf yeri ekle","katalog.mit_foto":"referans fotoğraflı","katalog.ohne_foto":"henüz referans fotoğraf yok",
 "katalog.bereich_neu":"Alan ekle","katalog.eigener_bereich":"Kendi adın …","katalog.referenzfoto":"Referans fotoğraf çek",
 "katalog.referenzfoto_erklaerung":"Her gün çekeceğin gibi bir kez çek. Fotoğraf taramada yardım olarak yarı saydam görünür.",
 "katalog.wirklich_loeschen":"Gerçekten silinsin mi? Geçmiş kalır.","katalog.name":"Ad","katalog.uebersetzen":"Diğer dilleri öner","katalog.vorschlag":"Öneri – lütfen kontrol et",
 "katalog.produkte_erklaerung":"Her ürünü bir kez fotoğrafla ve nasıl sayıldığını belirle. Yapay zekâ sadece birim sayar ve kendisi çevirir.",
 "katalog.produkt_neu":"Ürün ekle","katalog.noch_keine":"Henüz ürün yok.","katalog.foto":"Ürün fotoğrafı","katalog.foto_warum":"Yapay zekânın tanımasına yardım eder.",
 "katalog.kategorie":"Tür","katalog.wie_zaehlen":"Nasıl sayılıyor?","katalog.wie_zaehlen_unter":"Rafta ne görünüyor? Kasa, kova, adet …",
 "katalog.zaehleinheit":"Raftaki birim","katalog.inhalt":"Birim başına içerik (isteğe bağlı)","katalog.basiseinheit":"birim","katalog.beispiel":"1 {einheit} = {menge} {basis}",
 "katalog.mindestbestand":"En az ({einheit})","katalog.haltbarkeit":"Dayanır (gün)","katalog.preis":"{einheit} başına fiyat € (isteğe bağlı)","katalog.wo":"Nerede duruyor?",
 "kategorie.fleisch":"Et","kategorie.fisch":"Balık","kategorie.gemuese":"Sebze","kategorie.obst":"Meyve","kategorie.milch":"Süt ürünleri","kategorie.brot":"Ekmek ve hamur",
 "kategorie.tiefkuehl":"Dondurulmuş","kategorie.trocken":"Kuru gıda","kategorie.getraenke":"İçecek","kategorie.sonstiges":"Diğer",
 "kosten.titel":"Yapay zekâ maliyeti","kosten.letzte_30":"Son 30 gün","kosten.zeile":S("{n} çağrı · ort. {je} · ort. {tokens} token"),
 "kosten.keine":"Henüz maliyet yok.","kosten.je_betrieb":"İşletme başına","kosten.hinweis":"ABD dolarından sabit kurla çevrildi. Geçerli olan Anthropic faturasıdır.",
 "kosten.scan":"Tarama tanıma","kosten.assistent":"Asistan","kosten.briefing":"Özet","kosten.sprache":"Sesli giriş","kosten.uebersetzung":"Çeviriler","kosten.tagesgericht":"Günün yemeği",
 "aktion.einkaufsliste":"Alışveriş listesine ekle","aktion.bestand":"Stoku gör","aktion.verlust":"Özeti gör","aktion.einkauf":"Alışveriş listesini aç","aktion.neu_scannen":"Şimdi tara",
 "mhd.abgelaufen":"bozulmuş","mhd.heute":"bugün","mhd.morgen":"yarın","mhd.tage":S("{n} gün"),"mhd.in_tagen":S("{n} gün içinde"),
 "mitarbeiter.hallo":"Merhaba, {name}","mitarbeiter.sprache_waehlen":"Dil seç","mitarbeiter.heute":"Bugün taranacak","mitarbeiter.fortschritt":"{von} alandan {n} tamam",
 "mitarbeiter.jetzt_dran":"Sıradaki","mitarbeiter.erledigt":"Tamamlandı · {zeit}","mitarbeiter.offen":"Açık","mitarbeiter.bitte_bestaetigen":"Lütfen onayla",
 "mitarbeiter.weggeworfen":"Çöpe atıldı","mitarbeiter.erinnerung":"Saat {zeit} hatırlatması telefona gelsin","mitarbeiter.erinnerung_an":"Aç","mitarbeiter.keine_bereiche":"Henüz alan yok","mitarbeiter.keine_bereiche_unter":"Patron bunları kurulumda ekler.",
 "monat.1":"Ocak","monat.2":"Şubat","monat.3":"Mart","monat.4":"Nisan","monat.5":"Mayıs","monat.6":"Haziran","monat.7":"Temmuz","monat.8":"Ağustos","monat.9":"Eylül","monat.10":"Ekim","monat.11":"Kasım","monat.12":"Aralık",
 "nav.titel":"Ana menü","nav.assistent":"Asistan","nav.bestand":"Stok","nav.einkauf":"Alışveriş","nav.einkaufsliste":"Alışveriş listesi","nav.scannen":"Depoyu tara",
 "offline.kein_netz":"İnternet yok. Yine de tarayabilirsin.","offline.wird_hochgeladen":"İnternet gelince yüklenecek","offline.titel":"Telefona kaydedildi",
 "offline.wird_hochgeladen_lang":"Burada internet yok. Fotoğraflar telefonda güvende ve internet gelip uygulama açık olunca yüklenecek.",
 "offline.fehler":"Yükleme olmadı – tekrar için dokun",
 "rueckfrage.kurze_frage":"Kısa soru","rueckfrage.wie_viele":"Bu kaç {einheit} {produkt}?","rueckfrage.weiss_nicht":"Bilmiyorum",
 "scan.hinweis":"Tüm rafı çerçeveye al. Birkaç fotoğraf olabilir.","scan.geist_hinweis":"Kamerayı soluk resme göre hizala.","scan.geist_aus":"Yardım resmi kapalı","scan.geist_an":"Yardım resmi açık",
 "scan.lampe":"Fener","scan.foto":"Fotoğraf çek","scan.fotos":S("{n} fotoğraf"),"scan.letztes_weg":"Son fotoğrafı sil","scan.fertig":"Bitti","scan.naechste":"Sonraki yer",
 "scan.schaue_an":"Bir bakayım …","scan.erkennen_fehler":"Tanıma olmadı.","scan.liegt_auf_geraet":"Merak etme: fotoğraflar telefonda.",
 "scan.kamera_verweigert":"Kameraya izin yok. Lütfen telefon ayarlarından izin ver.","scan.kamera_fehler":"Kamera açılmıyor.",
 "splash.slogan":"Deposu her an gözünün önünde.",
 "sprache.willkommen":"Hoş geldin","sprache.frage":"Uygulamayı hangi dilde kullanmak istersin?","sprache.sprechen":"Konuş","sprache.fertig":"Konuşma bitti",
 "sprache.wandelt":"Dinliyorum …","sprache.nichts_verstanden":"Anlayamadım. Lütfen tekrar söyle veya yaz.",
 "team.titel":"Ekip","team.chef":"Patron","team.mitarbeiter":"Çalışan","team.einladen":"Çalışan davet et","team.code_ist":"Kod:","team.code_gueltig":"14 gün geçerli, bir kişi için.",
 "team.per_whatsapp":"WhatsApp ile gönder","team.link_kopieren":"Bağlantıyı kopyala","team.kopiert":"Kopyalandı.","team.entfernen":"Çıkar","team.wirklich_entfernen":"{name} gerçekten çıkarılsın mı?",
 "team.einladung_text":"Merhaba! The Chef'te {betrieb} ekibine davet edildin. Bağlantıyı aç: {link} – veya {code} kodunu gir.",
 "verlust.wert":"Çöpe atılan değer","verlust.vergleich":"{monat} ayına göre {betrag}","verlust.am_meisten":"En çok çöpe atılan","verlust.tipp":"Asistandan ipucu",
 "verlust.tipp_holen":"İpucu al","verlust.tipp_frage":"Bu ay en çok ne çöpe atıldı ve neyi daha iyi yapabilirim?","verlust.ohne_preis":S("fiyatsız {n} kayıt sayılmadı"),
 "vorlage.kuehlhaus":"Soğuk oda","vorlage.tiefkuehler":"Derin dondurucu","vorlage.trocken":"Kuru depo",
 "vorschlag.bestellen":"Ne sipariş etmeliyim?","vorschlag.haehnchen":"Tavuk hafta sonuna yeter mi?","vorschlag.weggeworfen":"Ne kadar çöpe atıldı?","vorschlag.tagesgericht":"Günün yemeği ne olsun?",
 "weg.frage":"Ne çöpe atıldı?","weg.wie_viel":"Ne kadar?","weg.gespeichert":"Kaydedildi.",
 "zahl.tippen":"Sayı yaz","zahl.sagen":"Sayıyı söyle","zahl.oder_sagen":"veya söyle","zahl.verstanden":"„{text}“ → {zahl}","zahl.nicht_verstanden":"„{text}“ – sayı anlaşılmadı. Lütfen yaz.",
 "zeit.nie":"hiç","zeit.heute":"bugün","zeit.gestern":"dün","zeit.heute_um":"bugün, {zeit}","zeit.gestern_um":"dün, {zeit}","zeit.vor_tagen":S("{n} gün önce"),
}
json.dump(dict(sorted(t.items())), open('public/sprachen/tr.json','w'), ensure_ascii=False, indent=1)
print(len(t))
